package com.ninyjun.erp.inventory.inventorysdk.model;

import java.util.Date;

public class InventoryLoss {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_LOSS.INVENTORY_LOSS_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Long inventoryLossId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_LOSS.INVENTORY_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Long inventoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_LOSS.STOREHOUSE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Integer storehouseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_LOSS.LOSS_AMOUNT
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Integer lossAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_LOSS.REASON_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Integer reasonCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_LOSS.REMARK
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_LOSS.CREATE_TIME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_LOSS.CREATE_EMP_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String createEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_LOSS.CREATE_DEPART_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String createDepartId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_LOSS.INVENTORY_LOSS_ID
     *
     * @return the value of INVENTORY_LOSS.INVENTORY_LOSS_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Long getInventoryLossId() {
        return inventoryLossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_LOSS.INVENTORY_LOSS_ID
     *
     * @param inventoryLossId the value for INVENTORY_LOSS.INVENTORY_LOSS_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setInventoryLossId(Long inventoryLossId) {
        this.inventoryLossId = inventoryLossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_LOSS.INVENTORY_ID
     *
     * @return the value of INVENTORY_LOSS.INVENTORY_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Long getInventoryId() {
        return inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_LOSS.INVENTORY_ID
     *
     * @param inventoryId the value for INVENTORY_LOSS.INVENTORY_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setInventoryId(Long inventoryId) {
        this.inventoryId = inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_LOSS.STOREHOUSE_CODE
     *
     * @return the value of INVENTORY_LOSS.STOREHOUSE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Integer getStorehouseCode() {
        return storehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_LOSS.STOREHOUSE_CODE
     *
     * @param storehouseCode the value for INVENTORY_LOSS.STOREHOUSE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setStorehouseCode(Integer storehouseCode) {
        this.storehouseCode = storehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_LOSS.LOSS_AMOUNT
     *
     * @return the value of INVENTORY_LOSS.LOSS_AMOUNT
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Integer getLossAmount() {
        return lossAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_LOSS.LOSS_AMOUNT
     *
     * @param lossAmount the value for INVENTORY_LOSS.LOSS_AMOUNT
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setLossAmount(Integer lossAmount) {
        this.lossAmount = lossAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_LOSS.REASON_CODE
     *
     * @return the value of INVENTORY_LOSS.REASON_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Integer getReasonCode() {
        return reasonCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_LOSS.REASON_CODE
     *
     * @param reasonCode the value for INVENTORY_LOSS.REASON_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setReasonCode(Integer reasonCode) {
        this.reasonCode = reasonCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_LOSS.REMARK
     *
     * @return the value of INVENTORY_LOSS.REMARK
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_LOSS.REMARK
     *
     * @param remark the value for INVENTORY_LOSS.REMARK
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_LOSS.CREATE_TIME
     *
     * @return the value of INVENTORY_LOSS.CREATE_TIME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_LOSS.CREATE_TIME
     *
     * @param createTime the value for INVENTORY_LOSS.CREATE_TIME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_LOSS.CREATE_EMP_ID
     *
     * @return the value of INVENTORY_LOSS.CREATE_EMP_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_LOSS.CREATE_EMP_ID
     *
     * @param createEmpId the value for INVENTORY_LOSS.CREATE_EMP_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_LOSS.CREATE_DEPART_ID
     *
     * @return the value of INVENTORY_LOSS.CREATE_DEPART_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getCreateDepartId() {
        return createDepartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_LOSS.CREATE_DEPART_ID
     *
     * @param createDepartId the value for INVENTORY_LOSS.CREATE_DEPART_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setCreateDepartId(String createDepartId) {
        this.createDepartId = createDepartId == null ? null : createDepartId.trim();
    }
}