package com.ninyjun.erp.inventory.inventorysdk.model;

import java.util.Date;

public class InventoryBatchNo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_BATCH_NO.INVENTORY_BATCH_NO_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Integer inventoryBatchNoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_BATCH_NO.PRODUCT_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Integer productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_BATCH_NO.BATCH_NO
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String batchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_BATCH_NO.MANUFACTURE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Integer manufactureCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_BATCH_NO.PRODUCE_DATE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Date produceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_BATCH_NO.INVALID_DATE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Date invalidDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_BATCH_NO.CREATE_TIME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_BATCH_NO.CREATE_EMP_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String createEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_BATCH_NO.CREATE_DEPART_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String createDepartId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_BATCH_NO.INVENTORY_BATCH_NO_ID
     *
     * @return the value of INVENTORY_BATCH_NO.INVENTORY_BATCH_NO_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Integer getInventoryBatchNoId() {
        return inventoryBatchNoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_BATCH_NO.INVENTORY_BATCH_NO_ID
     *
     * @param inventoryBatchNoId the value for INVENTORY_BATCH_NO.INVENTORY_BATCH_NO_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setInventoryBatchNoId(Integer inventoryBatchNoId) {
        this.inventoryBatchNoId = inventoryBatchNoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_BATCH_NO.PRODUCT_CODE
     *
     * @return the value of INVENTORY_BATCH_NO.PRODUCT_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Integer getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_BATCH_NO.PRODUCT_CODE
     *
     * @param productCode the value for INVENTORY_BATCH_NO.PRODUCT_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setProductCode(Integer productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_BATCH_NO.BATCH_NO
     *
     * @return the value of INVENTORY_BATCH_NO.BATCH_NO
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_BATCH_NO.BATCH_NO
     *
     * @param batchNo the value for INVENTORY_BATCH_NO.BATCH_NO
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_BATCH_NO.MANUFACTURE_CODE
     *
     * @return the value of INVENTORY_BATCH_NO.MANUFACTURE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Integer getManufactureCode() {
        return manufactureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_BATCH_NO.MANUFACTURE_CODE
     *
     * @param manufactureCode the value for INVENTORY_BATCH_NO.MANUFACTURE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setManufactureCode(Integer manufactureCode) {
        this.manufactureCode = manufactureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_BATCH_NO.PRODUCE_DATE
     *
     * @return the value of INVENTORY_BATCH_NO.PRODUCE_DATE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Date getProduceDate() {
        return produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_BATCH_NO.PRODUCE_DATE
     *
     * @param produceDate the value for INVENTORY_BATCH_NO.PRODUCE_DATE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setProduceDate(Date produceDate) {
        this.produceDate = produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_BATCH_NO.INVALID_DATE
     *
     * @return the value of INVENTORY_BATCH_NO.INVALID_DATE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Date getInvalidDate() {
        return invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_BATCH_NO.INVALID_DATE
     *
     * @param invalidDate the value for INVENTORY_BATCH_NO.INVALID_DATE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setInvalidDate(Date invalidDate) {
        this.invalidDate = invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_BATCH_NO.CREATE_TIME
     *
     * @return the value of INVENTORY_BATCH_NO.CREATE_TIME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_BATCH_NO.CREATE_TIME
     *
     * @param createTime the value for INVENTORY_BATCH_NO.CREATE_TIME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_BATCH_NO.CREATE_EMP_ID
     *
     * @return the value of INVENTORY_BATCH_NO.CREATE_EMP_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_BATCH_NO.CREATE_EMP_ID
     *
     * @param createEmpId the value for INVENTORY_BATCH_NO.CREATE_EMP_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_BATCH_NO.CREATE_DEPART_ID
     *
     * @return the value of INVENTORY_BATCH_NO.CREATE_DEPART_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getCreateDepartId() {
        return createDepartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_BATCH_NO.CREATE_DEPART_ID
     *
     * @param createDepartId the value for INVENTORY_BATCH_NO.CREATE_DEPART_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setCreateDepartId(String createDepartId) {
        this.createDepartId = createDepartId == null ? null : createDepartId.trim();
    }
}