package com.ninyjun.erp.inventory.inventorysdk.model;

public class InventoryStorehouse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_STOREHOUSE.STOREHOUSE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Integer storehouseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_STOREHOUSE.STOREHOUSE_NAME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String storehouseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_STOREHOUSE.ADDRESS
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_STOREHOUSE.TEL
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_STOREHOUSE.LINKMAN
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String linkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_STOREHOUSE.UP_STOREHOUSE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Integer upStorehouseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_STOREHOUSE.LEVEL
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_STOREHOUSE.STOREHOUSE_CODE
     *
     * @return the value of INVENTORY_STOREHOUSE.STOREHOUSE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Integer getStorehouseCode() {
        return storehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_STOREHOUSE.STOREHOUSE_CODE
     *
     * @param storehouseCode the value for INVENTORY_STOREHOUSE.STOREHOUSE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setStorehouseCode(Integer storehouseCode) {
        this.storehouseCode = storehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_STOREHOUSE.STOREHOUSE_NAME
     *
     * @return the value of INVENTORY_STOREHOUSE.STOREHOUSE_NAME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getStorehouseName() {
        return storehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_STOREHOUSE.STOREHOUSE_NAME
     *
     * @param storehouseName the value for INVENTORY_STOREHOUSE.STOREHOUSE_NAME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setStorehouseName(String storehouseName) {
        this.storehouseName = storehouseName == null ? null : storehouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_STOREHOUSE.ADDRESS
     *
     * @return the value of INVENTORY_STOREHOUSE.ADDRESS
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_STOREHOUSE.ADDRESS
     *
     * @param address the value for INVENTORY_STOREHOUSE.ADDRESS
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_STOREHOUSE.TEL
     *
     * @return the value of INVENTORY_STOREHOUSE.TEL
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_STOREHOUSE.TEL
     *
     * @param tel the value for INVENTORY_STOREHOUSE.TEL
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_STOREHOUSE.LINKMAN
     *
     * @return the value of INVENTORY_STOREHOUSE.LINKMAN
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_STOREHOUSE.LINKMAN
     *
     * @param linkman the value for INVENTORY_STOREHOUSE.LINKMAN
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_STOREHOUSE.UP_STOREHOUSE_CODE
     *
     * @return the value of INVENTORY_STOREHOUSE.UP_STOREHOUSE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Integer getUpStorehouseCode() {
        return upStorehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_STOREHOUSE.UP_STOREHOUSE_CODE
     *
     * @param upStorehouseCode the value for INVENTORY_STOREHOUSE.UP_STOREHOUSE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setUpStorehouseCode(Integer upStorehouseCode) {
        this.upStorehouseCode = upStorehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_STOREHOUSE.LEVEL
     *
     * @return the value of INVENTORY_STOREHOUSE.LEVEL
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_STOREHOUSE.LEVEL
     *
     * @param level the value for INVENTORY_STOREHOUSE.LEVEL
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}