package com.ninyjun.erp.inventory.inventorysdk.model;

import java.util.Date;

public class InventoryTransfer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_TRANSFER.TRANS_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Long transId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_TRANSFER.INVENTORY_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Long inventoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_TRANSFER.TRANS_SHEETNO
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String transSheetno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_TRANSFER.AMOUNT
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_TRANSFER.CREATE_TIME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_TRANSFER.CREATE_EMP_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String createEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_TRANSFER.CREATE_DEPART_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String createDepartId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_TRANSFER.TRANS_ID
     *
     * @return the value of INVENTORY_TRANSFER.TRANS_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Long getTransId() {
        return transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_TRANSFER.TRANS_ID
     *
     * @param transId the value for INVENTORY_TRANSFER.TRANS_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setTransId(Long transId) {
        this.transId = transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_TRANSFER.INVENTORY_ID
     *
     * @return the value of INVENTORY_TRANSFER.INVENTORY_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Long getInventoryId() {
        return inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_TRANSFER.INVENTORY_ID
     *
     * @param inventoryId the value for INVENTORY_TRANSFER.INVENTORY_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setInventoryId(Long inventoryId) {
        this.inventoryId = inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_TRANSFER.TRANS_SHEETNO
     *
     * @return the value of INVENTORY_TRANSFER.TRANS_SHEETNO
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getTransSheetno() {
        return transSheetno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_TRANSFER.TRANS_SHEETNO
     *
     * @param transSheetno the value for INVENTORY_TRANSFER.TRANS_SHEETNO
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setTransSheetno(String transSheetno) {
        this.transSheetno = transSheetno == null ? null : transSheetno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_TRANSFER.AMOUNT
     *
     * @return the value of INVENTORY_TRANSFER.AMOUNT
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_TRANSFER.AMOUNT
     *
     * @param amount the value for INVENTORY_TRANSFER.AMOUNT
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_TRANSFER.CREATE_TIME
     *
     * @return the value of INVENTORY_TRANSFER.CREATE_TIME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_TRANSFER.CREATE_TIME
     *
     * @param createTime the value for INVENTORY_TRANSFER.CREATE_TIME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_TRANSFER.CREATE_EMP_ID
     *
     * @return the value of INVENTORY_TRANSFER.CREATE_EMP_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_TRANSFER.CREATE_EMP_ID
     *
     * @param createEmpId the value for INVENTORY_TRANSFER.CREATE_EMP_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_TRANSFER.CREATE_DEPART_ID
     *
     * @return the value of INVENTORY_TRANSFER.CREATE_DEPART_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getCreateDepartId() {
        return createDepartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_TRANSFER.CREATE_DEPART_ID
     *
     * @param createDepartId the value for INVENTORY_TRANSFER.CREATE_DEPART_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setCreateDepartId(String createDepartId) {
        this.createDepartId = createDepartId == null ? null : createDepartId.trim();
    }
}