package com.ninyjun.erp.inventory.inventorysdk.model;

import java.util.Date;

public class Inventory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY.INVENTORY_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Long inventoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY.INVENTORY_BATCH_NO_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Integer inventoryBatchNoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY.PRODUCT_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Integer productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY.AMOUNT
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY.AMOUNT_LOSS
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Long amountLoss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY.STOREHOUSE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Integer storehouseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY.PRODUCE_DATE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Date produceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY.INVALID_DATE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Date invalidDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY.VERSION_NO
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Long versionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY.CREATE_TIME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY.CREATE_EMP_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String createEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY.CREATE_DEPART_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String createDepartId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY.INVENTORY_ID
     *
     * @return the value of INVENTORY.INVENTORY_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Long getInventoryId() {
        return inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY.INVENTORY_ID
     *
     * @param inventoryId the value for INVENTORY.INVENTORY_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setInventoryId(Long inventoryId) {
        this.inventoryId = inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY.INVENTORY_BATCH_NO_ID
     *
     * @return the value of INVENTORY.INVENTORY_BATCH_NO_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Integer getInventoryBatchNoId() {
        return inventoryBatchNoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY.INVENTORY_BATCH_NO_ID
     *
     * @param inventoryBatchNoId the value for INVENTORY.INVENTORY_BATCH_NO_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setInventoryBatchNoId(Integer inventoryBatchNoId) {
        this.inventoryBatchNoId = inventoryBatchNoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY.PRODUCT_CODE
     *
     * @return the value of INVENTORY.PRODUCT_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Integer getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY.PRODUCT_CODE
     *
     * @param productCode the value for INVENTORY.PRODUCT_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setProductCode(Integer productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY.AMOUNT
     *
     * @return the value of INVENTORY.AMOUNT
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY.AMOUNT
     *
     * @param amount the value for INVENTORY.AMOUNT
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY.AMOUNT_LOSS
     *
     * @return the value of INVENTORY.AMOUNT_LOSS
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Long getAmountLoss() {
        return amountLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY.AMOUNT_LOSS
     *
     * @param amountLoss the value for INVENTORY.AMOUNT_LOSS
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setAmountLoss(Long amountLoss) {
        this.amountLoss = amountLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY.STOREHOUSE_CODE
     *
     * @return the value of INVENTORY.STOREHOUSE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Integer getStorehouseCode() {
        return storehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY.STOREHOUSE_CODE
     *
     * @param storehouseCode the value for INVENTORY.STOREHOUSE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setStorehouseCode(Integer storehouseCode) {
        this.storehouseCode = storehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY.PRODUCE_DATE
     *
     * @return the value of INVENTORY.PRODUCE_DATE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Date getProduceDate() {
        return produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY.PRODUCE_DATE
     *
     * @param produceDate the value for INVENTORY.PRODUCE_DATE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setProduceDate(Date produceDate) {
        this.produceDate = produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY.INVALID_DATE
     *
     * @return the value of INVENTORY.INVALID_DATE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Date getInvalidDate() {
        return invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY.INVALID_DATE
     *
     * @param invalidDate the value for INVENTORY.INVALID_DATE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setInvalidDate(Date invalidDate) {
        this.invalidDate = invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY.VERSION_NO
     *
     * @return the value of INVENTORY.VERSION_NO
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Long getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY.VERSION_NO
     *
     * @param versionNo the value for INVENTORY.VERSION_NO
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setVersionNo(Long versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY.CREATE_TIME
     *
     * @return the value of INVENTORY.CREATE_TIME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY.CREATE_TIME
     *
     * @param createTime the value for INVENTORY.CREATE_TIME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY.CREATE_EMP_ID
     *
     * @return the value of INVENTORY.CREATE_EMP_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY.CREATE_EMP_ID
     *
     * @param createEmpId the value for INVENTORY.CREATE_EMP_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY.CREATE_DEPART_ID
     *
     * @return the value of INVENTORY.CREATE_DEPART_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getCreateDepartId() {
        return createDepartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY.CREATE_DEPART_ID
     *
     * @param createDepartId the value for INVENTORY.CREATE_DEPART_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setCreateDepartId(String createDepartId) {
        this.createDepartId = createDepartId == null ? null : createDepartId.trim();
    }
}