package com.ninyjun.erp.inventory.inventorysdk.model;

public class InventoryInoutRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_INOUT_REL.INVENTORY_INOUT_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Long inventoryInoutId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_INOUT_REL.RELATION_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Long relationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY_INOUT_REL.TRADE_TYPE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Integer tradeType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_INOUT_REL.INVENTORY_INOUT_ID
     *
     * @return the value of INVENTORY_INOUT_REL.INVENTORY_INOUT_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Long getInventoryInoutId() {
        return inventoryInoutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_INOUT_REL.INVENTORY_INOUT_ID
     *
     * @param inventoryInoutId the value for INVENTORY_INOUT_REL.INVENTORY_INOUT_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setInventoryInoutId(Long inventoryInoutId) {
        this.inventoryInoutId = inventoryInoutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_INOUT_REL.RELATION_ID
     *
     * @return the value of INVENTORY_INOUT_REL.RELATION_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Long getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_INOUT_REL.RELATION_ID
     *
     * @param relationId the value for INVENTORY_INOUT_REL.RELATION_ID
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setRelationId(Long relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY_INOUT_REL.TRADE_TYPE
     *
     * @return the value of INVENTORY_INOUT_REL.TRADE_TYPE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Integer getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY_INOUT_REL.TRADE_TYPE
     *
     * @param tradeType the value for INVENTORY_INOUT_REL.TRADE_TYPE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setTradeType(Integer tradeType) {
        this.tradeType = tradeType;
    }
}