package com.ninyjun.erp.inventory.inventorysdk.model;

public class Manafacturer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAFACTURER.MANUFACTURE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private Integer manufactureCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAFACTURER.MANUFACTURE_NAME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String manufactureName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAFACTURER.MANUFACTURE_PYM
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String manufacturePym;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAFACTURER.ADDRESS
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAFACTURER.TEL
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAFACTURER.FAX
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAFACTURER.POST_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAFACTURER.LINK_MAN
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    private String linkMan;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAFACTURER.MANUFACTURE_CODE
     *
     * @return the value of MANAFACTURER.MANUFACTURE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public Integer getManufactureCode() {
        return manufactureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAFACTURER.MANUFACTURE_CODE
     *
     * @param manufactureCode the value for MANAFACTURER.MANUFACTURE_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setManufactureCode(Integer manufactureCode) {
        this.manufactureCode = manufactureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAFACTURER.MANUFACTURE_NAME
     *
     * @return the value of MANAFACTURER.MANUFACTURE_NAME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getManufactureName() {
        return manufactureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAFACTURER.MANUFACTURE_NAME
     *
     * @param manufactureName the value for MANAFACTURER.MANUFACTURE_NAME
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setManufactureName(String manufactureName) {
        this.manufactureName = manufactureName == null ? null : manufactureName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAFACTURER.MANUFACTURE_PYM
     *
     * @return the value of MANAFACTURER.MANUFACTURE_PYM
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getManufacturePym() {
        return manufacturePym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAFACTURER.MANUFACTURE_PYM
     *
     * @param manufacturePym the value for MANAFACTURER.MANUFACTURE_PYM
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setManufacturePym(String manufacturePym) {
        this.manufacturePym = manufacturePym == null ? null : manufacturePym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAFACTURER.ADDRESS
     *
     * @return the value of MANAFACTURER.ADDRESS
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAFACTURER.ADDRESS
     *
     * @param address the value for MANAFACTURER.ADDRESS
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAFACTURER.TEL
     *
     * @return the value of MANAFACTURER.TEL
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAFACTURER.TEL
     *
     * @param tel the value for MANAFACTURER.TEL
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAFACTURER.FAX
     *
     * @return the value of MANAFACTURER.FAX
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAFACTURER.FAX
     *
     * @param fax the value for MANAFACTURER.FAX
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAFACTURER.POST_CODE
     *
     * @return the value of MANAFACTURER.POST_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAFACTURER.POST_CODE
     *
     * @param postCode the value for MANAFACTURER.POST_CODE
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAFACTURER.LINK_MAN
     *
     * @return the value of MANAFACTURER.LINK_MAN
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAFACTURER.LINK_MAN
     *
     * @param linkMan the value for MANAFACTURER.LINK_MAN
     *
     * @mbg.generated Mon Dec 02 16:05:08 CST 2019
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan == null ? null : linkMan.trim();
    }
}