package com.ninyjun.erp.customer.custsdk.model;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_NAME
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private String custName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_DESCRIBE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private String custDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CREATE_TIME
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CREATE_EMP_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private String createEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CREATE_DEPART_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private String createDepartId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_ID
     *
     * @return the value of CUSTOMER.CUST_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_ID
     *
     * @param custId the value for CUSTOMER.CUST_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_NAME
     *
     * @return the value of CUSTOMER.CUST_NAME
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_NAME
     *
     * @param custName the value for CUSTOMER.CUST_NAME
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_DESCRIBE
     *
     * @return the value of CUSTOMER.CUST_DESCRIBE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public String getCustDescribe() {
        return custDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_DESCRIBE
     *
     * @param custDescribe the value for CUSTOMER.CUST_DESCRIBE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCustDescribe(String custDescribe) {
        this.custDescribe = custDescribe == null ? null : custDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CREATE_TIME
     *
     * @return the value of CUSTOMER.CREATE_TIME
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CREATE_TIME
     *
     * @param createTime the value for CUSTOMER.CREATE_TIME
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CREATE_EMP_ID
     *
     * @return the value of CUSTOMER.CREATE_EMP_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CREATE_EMP_ID
     *
     * @param createEmpId the value for CUSTOMER.CREATE_EMP_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CREATE_DEPART_ID
     *
     * @return the value of CUSTOMER.CREATE_DEPART_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public String getCreateDepartId() {
        return createDepartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CREATE_DEPART_ID
     *
     * @param createDepartId the value for CUSTOMER.CREATE_DEPART_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCreateDepartId(String createDepartId) {
        this.createDepartId = createDepartId == null ? null : createDepartId.trim();
    }
}