package com.ninyjun.erp.customer.custsdk.model;

import java.util.Date;

public class CustomerVip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_VIP.CUST_VIP_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private Long custVipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_VIP.CUST_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_VIP.VIP_GRADE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private Integer vipGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_VIP.START_DATE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_VIP.END_DATAE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private Date endDatae;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_VIP.CUST_VIP_ID
     *
     * @return the value of CUSTOMER_VIP.CUST_VIP_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public Long getCustVipId() {
        return custVipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_VIP.CUST_VIP_ID
     *
     * @param custVipId the value for CUSTOMER_VIP.CUST_VIP_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCustVipId(Long custVipId) {
        this.custVipId = custVipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_VIP.CUST_ID
     *
     * @return the value of CUSTOMER_VIP.CUST_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_VIP.CUST_ID
     *
     * @param custId the value for CUSTOMER_VIP.CUST_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_VIP.VIP_GRADE
     *
     * @return the value of CUSTOMER_VIP.VIP_GRADE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public Integer getVipGrade() {
        return vipGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_VIP.VIP_GRADE
     *
     * @param vipGrade the value for CUSTOMER_VIP.VIP_GRADE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setVipGrade(Integer vipGrade) {
        this.vipGrade = vipGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_VIP.START_DATE
     *
     * @return the value of CUSTOMER_VIP.START_DATE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_VIP.START_DATE
     *
     * @param startDate the value for CUSTOMER_VIP.START_DATE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_VIP.END_DATAE
     *
     * @return the value of CUSTOMER_VIP.END_DATAE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public Date getEndDatae() {
        return endDatae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_VIP.END_DATAE
     *
     * @param endDatae the value for CUSTOMER_VIP.END_DATAE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setEndDatae(Date endDatae) {
        this.endDatae = endDatae;
    }
}