package com.ninyjun.erp.customer.custsdk.model;

public class CustomerAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_ADDRESS.CUST_ADDRESS_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private Long custAddressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_ADDRESS.CUST_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_ADDRESS.NATIONALITY
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_ADDRESS.PROVINCE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_ADDRESS.CITY
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_ADDRESS.POST_CODE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_ADDRESS.CUST_ADDRESS
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private String custAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_ADDRESS.CUST_ADDRESS_ID
     *
     * @return the value of CUSTOMER_ADDRESS.CUST_ADDRESS_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public Long getCustAddressId() {
        return custAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_ADDRESS.CUST_ADDRESS_ID
     *
     * @param custAddressId the value for CUSTOMER_ADDRESS.CUST_ADDRESS_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCustAddressId(Long custAddressId) {
        this.custAddressId = custAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_ADDRESS.CUST_ID
     *
     * @return the value of CUSTOMER_ADDRESS.CUST_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_ADDRESS.CUST_ID
     *
     * @param custId the value for CUSTOMER_ADDRESS.CUST_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_ADDRESS.NATIONALITY
     *
     * @return the value of CUSTOMER_ADDRESS.NATIONALITY
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_ADDRESS.NATIONALITY
     *
     * @param nationality the value for CUSTOMER_ADDRESS.NATIONALITY
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_ADDRESS.PROVINCE
     *
     * @return the value of CUSTOMER_ADDRESS.PROVINCE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_ADDRESS.PROVINCE
     *
     * @param province the value for CUSTOMER_ADDRESS.PROVINCE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_ADDRESS.CITY
     *
     * @return the value of CUSTOMER_ADDRESS.CITY
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_ADDRESS.CITY
     *
     * @param city the value for CUSTOMER_ADDRESS.CITY
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_ADDRESS.POST_CODE
     *
     * @return the value of CUSTOMER_ADDRESS.POST_CODE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_ADDRESS.POST_CODE
     *
     * @param postCode the value for CUSTOMER_ADDRESS.POST_CODE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_ADDRESS.CUST_ADDRESS
     *
     * @return the value of CUSTOMER_ADDRESS.CUST_ADDRESS
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public String getCustAddress() {
        return custAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_ADDRESS.CUST_ADDRESS
     *
     * @param custAddress the value for CUSTOMER_ADDRESS.CUST_ADDRESS
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCustAddress(String custAddress) {
        this.custAddress = custAddress == null ? null : custAddress.trim();
    }
}