package com.ninyjun.erp.customer.custsdk.model;

public class CustomerComminfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_COMMINFO.CUSTOMER_COMM_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private Long customerCommId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_COMMINFO.CUST_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_COMMINFO.COMM_TYPE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private Integer commType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_COMMINFO.COMM_IDENTIFY
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private String commIdentify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_COMMINFO.CUSTOMER_COMM_ID
     *
     * @return the value of CUSTOMER_COMMINFO.CUSTOMER_COMM_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public Long getCustomerCommId() {
        return customerCommId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_COMMINFO.CUSTOMER_COMM_ID
     *
     * @param customerCommId the value for CUSTOMER_COMMINFO.CUSTOMER_COMM_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCustomerCommId(Long customerCommId) {
        this.customerCommId = customerCommId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_COMMINFO.CUST_ID
     *
     * @return the value of CUSTOMER_COMMINFO.CUST_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_COMMINFO.CUST_ID
     *
     * @param custId the value for CUSTOMER_COMMINFO.CUST_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_COMMINFO.COMM_TYPE
     *
     * @return the value of CUSTOMER_COMMINFO.COMM_TYPE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public Integer getCommType() {
        return commType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_COMMINFO.COMM_TYPE
     *
     * @param commType the value for CUSTOMER_COMMINFO.COMM_TYPE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCommType(Integer commType) {
        this.commType = commType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_COMMINFO.COMM_IDENTIFY
     *
     * @return the value of CUSTOMER_COMMINFO.COMM_IDENTIFY
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public String getCommIdentify() {
        return commIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_COMMINFO.COMM_IDENTIFY
     *
     * @param commIdentify the value for CUSTOMER_COMMINFO.COMM_IDENTIFY
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCommIdentify(String commIdentify) {
        this.commIdentify = commIdentify == null ? null : commIdentify.trim();
    }
}