package com.ninyjun.erp.customer.custsdk.model;

public class CustomerExtra {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_EXTRA.CUST_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_EXTRA.PROPERTY_CODE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private String propertyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER_EXTRA.PROPERTY_VALUE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    private String propertyValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_EXTRA.CUST_ID
     *
     * @return the value of CUSTOMER_EXTRA.CUST_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_EXTRA.CUST_ID
     *
     * @param custId the value for CUSTOMER_EXTRA.CUST_ID
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_EXTRA.PROPERTY_CODE
     *
     * @return the value of CUSTOMER_EXTRA.PROPERTY_CODE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public String getPropertyCode() {
        return propertyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_EXTRA.PROPERTY_CODE
     *
     * @param propertyCode the value for CUSTOMER_EXTRA.PROPERTY_CODE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setPropertyCode(String propertyCode) {
        this.propertyCode = propertyCode == null ? null : propertyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER_EXTRA.PROPERTY_VALUE
     *
     * @return the value of CUSTOMER_EXTRA.PROPERTY_VALUE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public String getPropertyValue() {
        return propertyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER_EXTRA.PROPERTY_VALUE
     *
     * @param propertyValue the value for CUSTOMER_EXTRA.PROPERTY_VALUE
     *
     * @mbg.generated Sun Dec 01 09:57:30 CST 2019
     */
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue == null ? null : propertyValue.trim();
    }
}