package com.ninyjun.erp.order.chargesvc.repository;

import java.util.List;

import com.ninyjun.erp.order.ordersdk.model.ChargeExtra;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ChargeExtraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_EXTRA
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Delete({
        "delete from CHARGE_EXTRA",
        "where CHARGE_ID = #{chargeId,jdbcType=BIGINT}",
          "and PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("chargeId") Long chargeId, @Param("propertyCode") String propertyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_EXTRA
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Insert({
        "insert into CHARGE_EXTRA (CHARGE_ID, PROPERTY_CODE, ",
        "PROPERTY_VALUE)",
        "values (#{chargeId,jdbcType=BIGINT}, #{propertyCode,jdbcType=VARCHAR}, ",
        "#{propertyValue,jdbcType=VARCHAR})"
    })
    int insert(ChargeExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_EXTRA
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Select({
        "select",
        "CHARGE_ID, PROPERTY_CODE, PROPERTY_VALUE",
        "from CHARGE_EXTRA",
        "where CHARGE_ID = #{chargeId,jdbcType=BIGINT}",
          "and PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="CHARGE_ID", property="chargeId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="PROPERTY_CODE", property="propertyCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PROPERTY_VALUE", property="propertyValue", jdbcType=JdbcType.VARCHAR)
    })
    ChargeExtra selectByPrimaryKey(@Param("chargeId") Long chargeId, @Param("propertyCode") String propertyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_EXTRA
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Select({
        "select",
        "CHARGE_ID, PROPERTY_CODE, PROPERTY_VALUE",
        "from CHARGE_EXTRA"
    })
    @Results({
        @Result(column="CHARGE_ID", property="chargeId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="PROPERTY_CODE", property="propertyCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PROPERTY_VALUE", property="propertyValue", jdbcType=JdbcType.VARCHAR)
    })
    List<ChargeExtra> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_EXTRA
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Update({
        "update CHARGE_EXTRA",
        "set PROPERTY_VALUE = #{propertyValue,jdbcType=VARCHAR}",
        "where CHARGE_ID = #{chargeId,jdbcType=BIGINT}",
          "and PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ChargeExtra record);
}