package com.ninyjun.erp.order.chargesvc.repository;

import java.util.List;

import com.ninyjun.erp.order.ordersdk.model.Charge;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ChargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Delete({
        "delete from CHARGE",
        "where CHARGE_ID = #{chargeId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long chargeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Insert({
        "insert into CHARGE (CHARGE_ID, CUST_ID, ",
        "ACCT_ID, CHARGE_FEE, ",
        "CHANNEL_CODE, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID)",
        "values (#{chargeId,jdbcType=BIGINT}, #{custId,jdbcType=BIGINT}, ",
        "#{acctId,jdbcType=BIGINT}, #{chargeFee,jdbcType=BIGINT}, ",
        "#{channelCode,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{createEmpId,jdbcType=VARCHAR}, #{createDepartId,jdbcType=VARCHAR})"
    })
    int insert(Charge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Select({
        "select",
        "CHARGE_ID, CUST_ID, ACCT_ID, CHARGE_FEE, CHANNEL_CODE, CREATE_TIME, CREATE_EMP_ID, ",
        "CREATE_DEPART_ID",
        "from CHARGE",
        "where CHARGE_ID = #{chargeId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="CHARGE_ID", property="chargeId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT),
        @Result(column="ACCT_ID", property="acctId", jdbcType=JdbcType.BIGINT),
        @Result(column="CHARGE_FEE", property="chargeFee", jdbcType=JdbcType.BIGINT),
        @Result(column="CHANNEL_CODE", property="channelCode", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    Charge selectByPrimaryKey(Long chargeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Select({
        "select",
        "CHARGE_ID, CUST_ID, ACCT_ID, CHARGE_FEE, CHANNEL_CODE, CREATE_TIME, CREATE_EMP_ID, ",
        "CREATE_DEPART_ID",
        "from CHARGE"
    })
    @Results({
        @Result(column="CHARGE_ID", property="chargeId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT),
        @Result(column="ACCT_ID", property="acctId", jdbcType=JdbcType.BIGINT),
        @Result(column="CHARGE_FEE", property="chargeFee", jdbcType=JdbcType.BIGINT),
        @Result(column="CHANNEL_CODE", property="channelCode", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    List<Charge> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Update({
        "update CHARGE",
        "set CUST_ID = #{custId,jdbcType=BIGINT},",
          "ACCT_ID = #{acctId,jdbcType=BIGINT},",
          "CHARGE_FEE = #{chargeFee,jdbcType=BIGINT},",
          "CHANNEL_CODE = #{channelCode,jdbcType=INTEGER},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "CREATE_EMP_ID = #{createEmpId,jdbcType=VARCHAR},",
          "CREATE_DEPART_ID = #{createDepartId,jdbcType=VARCHAR}",
        "where CHARGE_ID = #{chargeId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Charge record);
}