package com.ninyjun.erp.order.chargesvc.repository;

import java.util.List;

import com.ninyjun.erp.order.ordersdk.model.ChargeChannel;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ChargeChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_CHANNEL
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Delete({
        "delete from CHARGE_CHANNEL",
        "where CHANNEL_CODE = #{channelCode,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer channelCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_CHANNEL
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Insert({
        "insert into CHARGE_CHANNEL (CHANNEL_CODE, CHANNEL_NAME, ",
        "CHANNEL_DESCRIBE)",
        "values (#{channelCode,jdbcType=INTEGER}, #{channelName,jdbcType=VARCHAR}, ",
        "#{channelDescribe,jdbcType=VARCHAR})"
    })
    int insert(ChargeChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_CHANNEL
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Select({
        "select",
        "CHANNEL_CODE, CHANNEL_NAME, CHANNEL_DESCRIBE",
        "from CHARGE_CHANNEL",
        "where CHANNEL_CODE = #{channelCode,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="CHANNEL_CODE", property="channelCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="CHANNEL_NAME", property="channelName", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHANNEL_DESCRIBE", property="channelDescribe", jdbcType=JdbcType.VARCHAR)
    })
    ChargeChannel selectByPrimaryKey(Integer channelCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_CHANNEL
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Select({
        "select",
        "CHANNEL_CODE, CHANNEL_NAME, CHANNEL_DESCRIBE",
        "from CHARGE_CHANNEL"
    })
    @Results({
        @Result(column="CHANNEL_CODE", property="channelCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="CHANNEL_NAME", property="channelName", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHANNEL_DESCRIBE", property="channelDescribe", jdbcType=JdbcType.VARCHAR)
    })
    List<ChargeChannel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_CHANNEL
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Update({
        "update CHARGE_CHANNEL",
        "set CHANNEL_NAME = #{channelName,jdbcType=VARCHAR},",
          "CHANNEL_DESCRIBE = #{channelDescribe,jdbcType=VARCHAR}",
        "where CHANNEL_CODE = #{channelCode,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ChargeChannel record);
}