package com.ninyjun.erp.order.chargesvc.repository;

import java.util.List;

import com.ninyjun.erp.order.ordersdk.model.ChargeCancel;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ChargeCancelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_CANCEL
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Delete({
        "delete from CHARGE_CANCEL",
        "where CHARGE_ID = #{chargeId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long chargeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_CANCEL
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Insert({
        "insert into CHARGE_CANCEL (CHARGE_ID, CHARGE_ID_NEW, ",
        "REASON_CODE, CANCEL_DESCRIBE, ",
        "CANCEL_TAG, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID)",
        "values (#{chargeId,jdbcType=BIGINT}, #{chargeIdNew,jdbcType=BIGINT}, ",
        "#{reasonCode,jdbcType=INTEGER}, #{cancelDescribe,jdbcType=VARCHAR}, ",
        "#{cancelTag,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{createEmpId,jdbcType=VARCHAR}, #{createDepartId,jdbcType=VARCHAR})"
    })
    int insert(ChargeCancel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_CANCEL
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Select({
        "select",
        "CHARGE_ID, CHARGE_ID_NEW, REASON_CODE, CANCEL_DESCRIBE, CANCEL_TAG, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID",
        "from CHARGE_CANCEL",
        "where CHARGE_ID = #{chargeId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="CHARGE_ID", property="chargeId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CHARGE_ID_NEW", property="chargeIdNew", jdbcType=JdbcType.BIGINT),
        @Result(column="REASON_CODE", property="reasonCode", jdbcType=JdbcType.INTEGER),
        @Result(column="CANCEL_DESCRIBE", property="cancelDescribe", jdbcType=JdbcType.VARCHAR),
        @Result(column="CANCEL_TAG", property="cancelTag", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    ChargeCancel selectByPrimaryKey(Long chargeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_CANCEL
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Select({
        "select",
        "CHARGE_ID, CHARGE_ID_NEW, REASON_CODE, CANCEL_DESCRIBE, CANCEL_TAG, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID",
        "from CHARGE_CANCEL"
    })
    @Results({
        @Result(column="CHARGE_ID", property="chargeId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CHARGE_ID_NEW", property="chargeIdNew", jdbcType=JdbcType.BIGINT),
        @Result(column="REASON_CODE", property="reasonCode", jdbcType=JdbcType.INTEGER),
        @Result(column="CANCEL_DESCRIBE", property="cancelDescribe", jdbcType=JdbcType.VARCHAR),
        @Result(column="CANCEL_TAG", property="cancelTag", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    List<ChargeCancel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_CANCEL
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Update({
        "update CHARGE_CANCEL",
        "set CHARGE_ID_NEW = #{chargeIdNew,jdbcType=BIGINT},",
          "REASON_CODE = #{reasonCode,jdbcType=INTEGER},",
          "CANCEL_DESCRIBE = #{cancelDescribe,jdbcType=VARCHAR},",
          "CANCEL_TAG = #{cancelTag,jdbcType=INTEGER},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "CREATE_EMP_ID = #{createEmpId,jdbcType=VARCHAR},",
          "CREATE_DEPART_ID = #{createDepartId,jdbcType=VARCHAR}",
        "where CHARGE_ID = #{chargeId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ChargeCancel record);
}