package com.ninyjun.erp.order.chargesvc.repository;

import java.util.List;

import com.ninyjun.erp.order.ordersdk.model.ChargePayVoucher;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ChargePayVoucherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_PAY_VOUCHER
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Delete({
        "delete from CHARGE_PAY_VOUCHER",
        "where CHARGE_PAY_VOUCHER_ID = #{chargePayVoucherId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long chargePayVoucherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_PAY_VOUCHER
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Insert({
        "insert into CHARGE_PAY_VOUCHER (CHARGE_PAY_VOUCHER_ID, CHARGE_ID, ",
        "PAY_MODE, PAY_VOUCHER_NO, ",
        "PAY_FEE, FINANCIAL_CODE, ",
        "FINANCIAL_NAME, CARD_NO, ",
        "INVALID_DATE)",
        "values (#{chargePayVoucherId,jdbcType=BIGINT}, #{chargeId,jdbcType=BIGINT}, ",
        "#{payMode,jdbcType=INTEGER}, #{payVoucherNo,jdbcType=VARCHAR}, ",
        "#{payFee,jdbcType=BIGINT}, #{financialCode,jdbcType=VARCHAR}, ",
        "#{financialName,jdbcType=VARCHAR}, #{cardNo,jdbcType=VARCHAR}, ",
        "#{invalidDate,jdbcType=TIMESTAMP})"
    })
    int insert(ChargePayVoucher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_PAY_VOUCHER
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Select({
        "select",
        "CHARGE_PAY_VOUCHER_ID, CHARGE_ID, PAY_MODE, PAY_VOUCHER_NO, PAY_FEE, FINANCIAL_CODE, ",
        "FINANCIAL_NAME, CARD_NO, INVALID_DATE",
        "from CHARGE_PAY_VOUCHER",
        "where CHARGE_PAY_VOUCHER_ID = #{chargePayVoucherId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="CHARGE_PAY_VOUCHER_ID", property="chargePayVoucherId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CHARGE_ID", property="chargeId", jdbcType=JdbcType.BIGINT),
        @Result(column="PAY_MODE", property="payMode", jdbcType=JdbcType.INTEGER),
        @Result(column="PAY_VOUCHER_NO", property="payVoucherNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAY_FEE", property="payFee", jdbcType=JdbcType.BIGINT),
        @Result(column="FINANCIAL_CODE", property="financialCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="FINANCIAL_NAME", property="financialName", jdbcType=JdbcType.VARCHAR),
        @Result(column="CARD_NO", property="cardNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="INVALID_DATE", property="invalidDate", jdbcType=JdbcType.TIMESTAMP)
    })
    ChargePayVoucher selectByPrimaryKey(Long chargePayVoucherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_PAY_VOUCHER
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Select({
        "select",
        "CHARGE_PAY_VOUCHER_ID, CHARGE_ID, PAY_MODE, PAY_VOUCHER_NO, PAY_FEE, FINANCIAL_CODE, ",
        "FINANCIAL_NAME, CARD_NO, INVALID_DATE",
        "from CHARGE_PAY_VOUCHER"
    })
    @Results({
        @Result(column="CHARGE_PAY_VOUCHER_ID", property="chargePayVoucherId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CHARGE_ID", property="chargeId", jdbcType=JdbcType.BIGINT),
        @Result(column="PAY_MODE", property="payMode", jdbcType=JdbcType.INTEGER),
        @Result(column="PAY_VOUCHER_NO", property="payVoucherNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAY_FEE", property="payFee", jdbcType=JdbcType.BIGINT),
        @Result(column="FINANCIAL_CODE", property="financialCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="FINANCIAL_NAME", property="financialName", jdbcType=JdbcType.VARCHAR),
        @Result(column="CARD_NO", property="cardNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="INVALID_DATE", property="invalidDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<ChargePayVoucher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_PAY_VOUCHER
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Update({
        "update CHARGE_PAY_VOUCHER",
        "set CHARGE_ID = #{chargeId,jdbcType=BIGINT},",
          "PAY_MODE = #{payMode,jdbcType=INTEGER},",
          "PAY_VOUCHER_NO = #{payVoucherNo,jdbcType=VARCHAR},",
          "PAY_FEE = #{payFee,jdbcType=BIGINT},",
          "FINANCIAL_CODE = #{financialCode,jdbcType=VARCHAR},",
          "FINANCIAL_NAME = #{financialName,jdbcType=VARCHAR},",
          "CARD_NO = #{cardNo,jdbcType=VARCHAR},",
          "INVALID_DATE = #{invalidDate,jdbcType=TIMESTAMP}",
        "where CHARGE_PAY_VOUCHER_ID = #{chargePayVoucherId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ChargePayVoucher record);
}