package com.ninyjun.erp.order.chargesvc.repository;

import java.util.List;

import com.ninyjun.erp.order.ordersdk.model.ChargeAcctBalanceRe;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ChargeAcctBalanceReMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_ACCT_BALANCE_RE
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Delete({
        "delete from CHARGE_ACCT_BALANCE_RE",
        "where CHARGE_PAY_VOUCHER_ID = #{chargePayVoucherId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long chargePayVoucherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_ACCT_BALANCE_RE
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Insert({
        "insert into CHARGE_ACCT_BALANCE_RE (CHARGE_PAY_VOUCHER_ID, ACCT_BALANCE_RE_ID, ",
        "CHARGE_ID)",
        "values (#{chargePayVoucherId,jdbcType=BIGINT}, #{acctBalanceReId,jdbcType=BIGINT}, ",
        "#{chargeId,jdbcType=BIGINT})"
    })
    int insert(ChargeAcctBalanceRe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_ACCT_BALANCE_RE
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Select({
        "select",
        "CHARGE_PAY_VOUCHER_ID, ACCT_BALANCE_RE_ID, CHARGE_ID",
        "from CHARGE_ACCT_BALANCE_RE",
        "where CHARGE_PAY_VOUCHER_ID = #{chargePayVoucherId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="CHARGE_PAY_VOUCHER_ID", property="chargePayVoucherId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="ACCT_BALANCE_RE_ID", property="acctBalanceReId", jdbcType=JdbcType.BIGINT),
        @Result(column="CHARGE_ID", property="chargeId", jdbcType=JdbcType.BIGINT)
    })
    ChargeAcctBalanceRe selectByPrimaryKey(Long chargePayVoucherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_ACCT_BALANCE_RE
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Select({
        "select",
        "CHARGE_PAY_VOUCHER_ID, ACCT_BALANCE_RE_ID, CHARGE_ID",
        "from CHARGE_ACCT_BALANCE_RE"
    })
    @Results({
        @Result(column="CHARGE_PAY_VOUCHER_ID", property="chargePayVoucherId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="ACCT_BALANCE_RE_ID", property="acctBalanceReId", jdbcType=JdbcType.BIGINT),
        @Result(column="CHARGE_ID", property="chargeId", jdbcType=JdbcType.BIGINT)
    })
    List<ChargeAcctBalanceRe> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_ACCT_BALANCE_RE
     *
     * @mbg.generated Fri Nov 29 17:39:58 CST 2019
     */
    @Update({
        "update CHARGE_ACCT_BALANCE_RE",
        "set ACCT_BALANCE_RE_ID = #{acctBalanceReId,jdbcType=BIGINT},",
          "CHARGE_ID = #{chargeId,jdbcType=BIGINT}",
        "where CHARGE_PAY_VOUCHER_ID = #{chargePayVoucherId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ChargeAcctBalanceRe record);
}