package com.ninyjun.erp.account.acctbalancesvc.repository;

import java.util.List;

import com.ninyjun.erp.account.acctsdk.model.AccountBalanceReRel;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface AccountBalanceReRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BALANCE_RE_REL
     *
     * @mbg.generated Fri Nov 29 17:37:57 CST 2019
     */
    @Delete({
        "delete from ACCOUNT_BALANCE_RE_REL",
        "where ACCT_BALANCE_RE_ID = #{acctBalanceReId,jdbcType=BIGINT}",
          "and RELATION_ID = #{relationId,jdbcType=BIGINT}",
          "and TRADE_TYPE = #{tradeType,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("acctBalanceReId") Long acctBalanceReId, @Param("relationId") Long relationId, @Param("tradeType") Integer tradeType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BALANCE_RE_REL
     *
     * @mbg.generated Fri Nov 29 17:37:57 CST 2019
     */
    @Insert({
        "insert into ACCOUNT_BALANCE_RE_REL (ACCT_BALANCE_RE_ID, RELATION_ID, ",
        "TRADE_TYPE)",
        "values (#{acctBalanceReId,jdbcType=BIGINT}, #{relationId,jdbcType=BIGINT}, ",
        "#{tradeType,jdbcType=INTEGER})"
    })
    int insert(AccountBalanceReRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BALANCE_RE_REL
     *
     * @mbg.generated Fri Nov 29 17:37:57 CST 2019
     */
    @Select({
        "select",
        "ACCT_BALANCE_RE_ID, RELATION_ID, TRADE_TYPE",
        "from ACCOUNT_BALANCE_RE_REL"
    })
    @Results({
        @Result(column="ACCT_BALANCE_RE_ID", property="acctBalanceReId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="RELATION_ID", property="relationId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="TRADE_TYPE", property="tradeType", jdbcType=JdbcType.INTEGER, id=true)
    })
    List<AccountBalanceReRel> selectAll();
}