package com.ninyjun.erp.account.acctbalancesvc.repository;

import java.util.List;

import com.ninyjun.erp.account.acctsdk.model.AccountBalanceType;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface AccountBalanceTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BALANCE_TYPE
     *
     * @mbg.generated Fri Nov 29 17:37:57 CST 2019
     */
    @Delete({
        "delete from ACCOUNT_BALANCE_TYPE",
        "where ACCT_BALANCE_TYPE_CODE = #{acctBalanceTypeCode,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer acctBalanceTypeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BALANCE_TYPE
     *
     * @mbg.generated Fri Nov 29 17:37:57 CST 2019
     */
    @Insert({
        "insert into ACCOUNT_BALANCE_TYPE (ACCT_BALANCE_TYPE_CODE, ACCT_BALANCE_TYPE_NAME, ",
        "TYPE_CATALOG, TYPE_DESCRIBE)",
        "values (#{acctBalanceTypeCode,jdbcType=INTEGER}, #{acctBalanceTypeName,jdbcType=VARCHAR}, ",
        "#{typeCatalog,jdbcType=INTEGER}, #{typeDescribe,jdbcType=VARCHAR})"
    })
    int insert(AccountBalanceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BALANCE_TYPE
     *
     * @mbg.generated Fri Nov 29 17:37:57 CST 2019
     */
    @Select({
        "select",
        "ACCT_BALANCE_TYPE_CODE, ACCT_BALANCE_TYPE_NAME, TYPE_CATALOG, TYPE_DESCRIBE",
        "from ACCOUNT_BALANCE_TYPE",
        "where ACCT_BALANCE_TYPE_CODE = #{acctBalanceTypeCode,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ACCT_BALANCE_TYPE_CODE", property="acctBalanceTypeCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ACCT_BALANCE_TYPE_NAME", property="acctBalanceTypeName", jdbcType=JdbcType.VARCHAR),
        @Result(column="TYPE_CATALOG", property="typeCatalog", jdbcType=JdbcType.INTEGER),
        @Result(column="TYPE_DESCRIBE", property="typeDescribe", jdbcType=JdbcType.VARCHAR)
    })
    AccountBalanceType selectByPrimaryKey(Integer acctBalanceTypeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BALANCE_TYPE
     *
     * @mbg.generated Fri Nov 29 17:37:57 CST 2019
     */
    @Select({
        "select",
        "ACCT_BALANCE_TYPE_CODE, ACCT_BALANCE_TYPE_NAME, TYPE_CATALOG, TYPE_DESCRIBE",
        "from ACCOUNT_BALANCE_TYPE"
    })
    @Results({
        @Result(column="ACCT_BALANCE_TYPE_CODE", property="acctBalanceTypeCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ACCT_BALANCE_TYPE_NAME", property="acctBalanceTypeName", jdbcType=JdbcType.VARCHAR),
        @Result(column="TYPE_CATALOG", property="typeCatalog", jdbcType=JdbcType.INTEGER),
        @Result(column="TYPE_DESCRIBE", property="typeDescribe", jdbcType=JdbcType.VARCHAR)
    })
    List<AccountBalanceType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BALANCE_TYPE
     *
     * @mbg.generated Fri Nov 29 17:37:57 CST 2019
     */
    @Update({
        "update ACCOUNT_BALANCE_TYPE",
        "set ACCT_BALANCE_TYPE_NAME = #{acctBalanceTypeName,jdbcType=VARCHAR},",
          "TYPE_CATALOG = #{typeCatalog,jdbcType=INTEGER},",
          "TYPE_DESCRIBE = #{typeDescribe,jdbcType=VARCHAR}",
        "where ACCT_BALANCE_TYPE_CODE = #{acctBalanceTypeCode,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AccountBalanceType record);
}