package com.ninyjun.erp.account.acctbalancesvc.repository;

import java.util.List;

import com.ninyjun.erp.account.acctsdk.model.AccountBalanceExtra;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface AccountBalanceExtraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BALANCE_EXTRA
     *
     * @mbg.generated Fri Nov 29 17:37:57 CST 2019
     */
    @Delete({
        "delete from ACCOUNT_BALANCE_EXTRA",
        "where ACCT_BALANCE_ID = #{acctBalanceId,jdbcType=BIGINT}",
          "and PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("acctBalanceId") Long acctBalanceId, @Param("propertyCode") String propertyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BALANCE_EXTRA
     *
     * @mbg.generated Fri Nov 29 17:37:57 CST 2019
     */
    @Insert({
        "insert into ACCOUNT_BALANCE_EXTRA (ACCT_BALANCE_ID, PROPERTY_CODE, ",
        "PROPERTY_VALUE)",
        "values (#{acctBalanceId,jdbcType=BIGINT}, #{propertyCode,jdbcType=VARCHAR}, ",
        "#{propertyValue,jdbcType=VARCHAR})"
    })
    int insert(AccountBalanceExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BALANCE_EXTRA
     *
     * @mbg.generated Fri Nov 29 17:37:57 CST 2019
     */
    @Select({
        "select",
        "ACCT_BALANCE_ID, PROPERTY_CODE, PROPERTY_VALUE",
        "from ACCOUNT_BALANCE_EXTRA",
        "where ACCT_BALANCE_ID = #{acctBalanceId,jdbcType=BIGINT}",
          "and PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ACCT_BALANCE_ID", property="acctBalanceId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="PROPERTY_CODE", property="propertyCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PROPERTY_VALUE", property="propertyValue", jdbcType=JdbcType.VARCHAR)
    })
    AccountBalanceExtra selectByPrimaryKey(@Param("acctBalanceId") Long acctBalanceId, @Param("propertyCode") String propertyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BALANCE_EXTRA
     *
     * @mbg.generated Fri Nov 29 17:37:57 CST 2019
     */
    @Select({
        "select",
        "ACCT_BALANCE_ID, PROPERTY_CODE, PROPERTY_VALUE",
        "from ACCOUNT_BALANCE_EXTRA"
    })
    @Results({
        @Result(column="ACCT_BALANCE_ID", property="acctBalanceId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="PROPERTY_CODE", property="propertyCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PROPERTY_VALUE", property="propertyValue", jdbcType=JdbcType.VARCHAR)
    })
    List<AccountBalanceExtra> selectAll();


    @Select({
            "select",
            "ACCT_BALANCE_ID, PROPERTY_CODE, PROPERTY_VALUE",
            "from ACCOUNT_BALANCE_EXTRA",
            " where ACCT_BALANCE_ID = #{acctBalanceId,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="ACCT_BALANCE_ID", property="acctBalanceId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="PROPERTY_CODE", property="propertyCode", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="PROPERTY_VALUE", property="propertyValue", jdbcType=JdbcType.VARCHAR)
    })
    List<AccountBalanceExtra> selectByAcctBalanceId(Long acctBalanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BALANCE_EXTRA
     *
     * @mbg.generated Fri Nov 29 17:37:57 CST 2019
     */
    @Update({
        "update ACCOUNT_BALANCE_EXTRA",
        "set PROPERTY_VALUE = #{propertyValue,jdbcType=VARCHAR}",
        "where ACCT_BALANCE_ID = #{acctBalanceId,jdbcType=BIGINT}",
          "and PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(AccountBalanceExtra record);
}