package com.ninyjun.erp.order.ordersdk.model;

public class ChargeExtra {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_EXTRA.CHARGE_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Long chargeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_EXTRA.PROPERTY_CODE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private String propertyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_EXTRA.PROPERTY_VALUE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private String propertyValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_EXTRA.CHARGE_ID
     *
     * @return the value of CHARGE_EXTRA.CHARGE_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Long getChargeId() {
        return chargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_EXTRA.CHARGE_ID
     *
     * @param chargeId the value for CHARGE_EXTRA.CHARGE_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setChargeId(Long chargeId) {
        this.chargeId = chargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_EXTRA.PROPERTY_CODE
     *
     * @return the value of CHARGE_EXTRA.PROPERTY_CODE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public String getPropertyCode() {
        return propertyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_EXTRA.PROPERTY_CODE
     *
     * @param propertyCode the value for CHARGE_EXTRA.PROPERTY_CODE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setPropertyCode(String propertyCode) {
        this.propertyCode = propertyCode == null ? null : propertyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_EXTRA.PROPERTY_VALUE
     *
     * @return the value of CHARGE_EXTRA.PROPERTY_VALUE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public String getPropertyValue() {
        return propertyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_EXTRA.PROPERTY_VALUE
     *
     * @param propertyValue the value for CHARGE_EXTRA.PROPERTY_VALUE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue == null ? null : propertyValue.trim();
    }
}