package com.ninyjun.erp.order.ordersdk.model;

public class ChargeChannel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_CHANNEL.CHANNEL_CODE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Integer channelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_CHANNEL.CHANNEL_NAME
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private String channelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_CHANNEL.CHANNEL_DESCRIBE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private String channelDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_CHANNEL.CHANNEL_CODE
     *
     * @return the value of CHARGE_CHANNEL.CHANNEL_CODE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Integer getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_CHANNEL.CHANNEL_CODE
     *
     * @param channelCode the value for CHARGE_CHANNEL.CHANNEL_CODE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setChannelCode(Integer channelCode) {
        this.channelCode = channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_CHANNEL.CHANNEL_NAME
     *
     * @return the value of CHARGE_CHANNEL.CHANNEL_NAME
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_CHANNEL.CHANNEL_NAME
     *
     * @param channelName the value for CHARGE_CHANNEL.CHANNEL_NAME
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_CHANNEL.CHANNEL_DESCRIBE
     *
     * @return the value of CHARGE_CHANNEL.CHANNEL_DESCRIBE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public String getChannelDescribe() {
        return channelDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_CHANNEL.CHANNEL_DESCRIBE
     *
     * @param channelDescribe the value for CHARGE_CHANNEL.CHANNEL_DESCRIBE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setChannelDescribe(String channelDescribe) {
        this.channelDescribe = channelDescribe == null ? null : channelDescribe.trim();
    }
}