package com.ninyjun.erp.order.ordersdk.model;

public class ChargeAcctBalanceRe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_ACCT_BALANCE_RE.CHARGE_PAY_VOUCHER_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Long chargePayVoucherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_ACCT_BALANCE_RE.ACCT_BALANCE_RE_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Long acctBalanceReId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_ACCT_BALANCE_RE.CHARGE_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Long chargeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_ACCT_BALANCE_RE.CHARGE_PAY_VOUCHER_ID
     *
     * @return the value of CHARGE_ACCT_BALANCE_RE.CHARGE_PAY_VOUCHER_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Long getChargePayVoucherId() {
        return chargePayVoucherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_ACCT_BALANCE_RE.CHARGE_PAY_VOUCHER_ID
     *
     * @param chargePayVoucherId the value for CHARGE_ACCT_BALANCE_RE.CHARGE_PAY_VOUCHER_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setChargePayVoucherId(Long chargePayVoucherId) {
        this.chargePayVoucherId = chargePayVoucherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_ACCT_BALANCE_RE.ACCT_BALANCE_RE_ID
     *
     * @return the value of CHARGE_ACCT_BALANCE_RE.ACCT_BALANCE_RE_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Long getAcctBalanceReId() {
        return acctBalanceReId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_ACCT_BALANCE_RE.ACCT_BALANCE_RE_ID
     *
     * @param acctBalanceReId the value for CHARGE_ACCT_BALANCE_RE.ACCT_BALANCE_RE_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setAcctBalanceReId(Long acctBalanceReId) {
        this.acctBalanceReId = acctBalanceReId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_ACCT_BALANCE_RE.CHARGE_ID
     *
     * @return the value of CHARGE_ACCT_BALANCE_RE.CHARGE_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Long getChargeId() {
        return chargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_ACCT_BALANCE_RE.CHARGE_ID
     *
     * @param chargeId the value for CHARGE_ACCT_BALANCE_RE.CHARGE_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setChargeId(Long chargeId) {
        this.chargeId = chargeId;
    }
}