package com.ninyjun.erp.order.ordersdk.model;

import java.util.Date;

public class Charge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.CHARGE_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Long chargeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.CUST_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.ACCT_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Long acctId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.CHARGE_FEE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Long chargeFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.CHANNEL_CODE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Integer channelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.CREATE_TIME
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.CREATE_EMP_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private String createEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.CREATE_DEPART_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private String createDepartId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.CHARGE_ID
     *
     * @return the value of CHARGE.CHARGE_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Long getChargeId() {
        return chargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.CHARGE_ID
     *
     * @param chargeId the value for CHARGE.CHARGE_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setChargeId(Long chargeId) {
        this.chargeId = chargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.CUST_ID
     *
     * @return the value of CHARGE.CUST_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.CUST_ID
     *
     * @param custId the value for CHARGE.CUST_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.ACCT_ID
     *
     * @return the value of CHARGE.ACCT_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Long getAcctId() {
        return acctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.ACCT_ID
     *
     * @param acctId the value for CHARGE.ACCT_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setAcctId(Long acctId) {
        this.acctId = acctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.CHARGE_FEE
     *
     * @return the value of CHARGE.CHARGE_FEE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Long getChargeFee() {
        return chargeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.CHARGE_FEE
     *
     * @param chargeFee the value for CHARGE.CHARGE_FEE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setChargeFee(Long chargeFee) {
        this.chargeFee = chargeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.CHANNEL_CODE
     *
     * @return the value of CHARGE.CHANNEL_CODE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Integer getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.CHANNEL_CODE
     *
     * @param channelCode the value for CHARGE.CHANNEL_CODE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setChannelCode(Integer channelCode) {
        this.channelCode = channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.CREATE_TIME
     *
     * @return the value of CHARGE.CREATE_TIME
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.CREATE_TIME
     *
     * @param createTime the value for CHARGE.CREATE_TIME
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.CREATE_EMP_ID
     *
     * @return the value of CHARGE.CREATE_EMP_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.CREATE_EMP_ID
     *
     * @param createEmpId the value for CHARGE.CREATE_EMP_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.CREATE_DEPART_ID
     *
     * @return the value of CHARGE.CREATE_DEPART_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public String getCreateDepartId() {
        return createDepartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.CREATE_DEPART_ID
     *
     * @param createDepartId the value for CHARGE.CREATE_DEPART_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setCreateDepartId(String createDepartId) {
        this.createDepartId = createDepartId == null ? null : createDepartId.trim();
    }
}