package com.ninyjun.erp.order.ordersdk.model;

import java.util.Date;

public class SaleCancel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_CANCEL.SALE_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Long saleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_CANCEL.SALE_ID_NEW
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Long saleIdNew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_CANCEL.CANCEL_TAG
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Integer cancelTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_CANCEL.REASON_CODE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Integer reasonCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_CANCEL.CANCEL_DESCRIBE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private String cancelDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_CANCEL.CREATE_TIME
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_CANCEL.CREATE_EMP_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private String createEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_CANCEL.CREATE_DEPART_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    private String createDepartId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_CANCEL.SALE_ID
     *
     * @return the value of SALE_CANCEL.SALE_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Long getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_CANCEL.SALE_ID
     *
     * @param saleId the value for SALE_CANCEL.SALE_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setSaleId(Long saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_CANCEL.SALE_ID_NEW
     *
     * @return the value of SALE_CANCEL.SALE_ID_NEW
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Long getSaleIdNew() {
        return saleIdNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_CANCEL.SALE_ID_NEW
     *
     * @param saleIdNew the value for SALE_CANCEL.SALE_ID_NEW
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setSaleIdNew(Long saleIdNew) {
        this.saleIdNew = saleIdNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_CANCEL.CANCEL_TAG
     *
     * @return the value of SALE_CANCEL.CANCEL_TAG
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Integer getCancelTag() {
        return cancelTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_CANCEL.CANCEL_TAG
     *
     * @param cancelTag the value for SALE_CANCEL.CANCEL_TAG
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setCancelTag(Integer cancelTag) {
        this.cancelTag = cancelTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_CANCEL.REASON_CODE
     *
     * @return the value of SALE_CANCEL.REASON_CODE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Integer getReasonCode() {
        return reasonCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_CANCEL.REASON_CODE
     *
     * @param reasonCode the value for SALE_CANCEL.REASON_CODE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setReasonCode(Integer reasonCode) {
        this.reasonCode = reasonCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_CANCEL.CANCEL_DESCRIBE
     *
     * @return the value of SALE_CANCEL.CANCEL_DESCRIBE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public String getCancelDescribe() {
        return cancelDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_CANCEL.CANCEL_DESCRIBE
     *
     * @param cancelDescribe the value for SALE_CANCEL.CANCEL_DESCRIBE
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setCancelDescribe(String cancelDescribe) {
        this.cancelDescribe = cancelDescribe == null ? null : cancelDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_CANCEL.CREATE_TIME
     *
     * @return the value of SALE_CANCEL.CREATE_TIME
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_CANCEL.CREATE_TIME
     *
     * @param createTime the value for SALE_CANCEL.CREATE_TIME
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_CANCEL.CREATE_EMP_ID
     *
     * @return the value of SALE_CANCEL.CREATE_EMP_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_CANCEL.CREATE_EMP_ID
     *
     * @param createEmpId the value for SALE_CANCEL.CREATE_EMP_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_CANCEL.CREATE_DEPART_ID
     *
     * @return the value of SALE_CANCEL.CREATE_DEPART_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public String getCreateDepartId() {
        return createDepartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_CANCEL.CREATE_DEPART_ID
     *
     * @param createDepartId the value for SALE_CANCEL.CREATE_DEPART_ID
     *
     * @mbg.generated Sun Dec 01 11:13:29 CST 2019
     */
    public void setCreateDepartId(String createDepartId) {
        this.createDepartId = createDepartId == null ? null : createDepartId.trim();
    }
}