package com.ninyjun.erp.customer.custsvc.repository;

import java.util.List;

import com.ninyjun.erp.customer.custsdk.model.CustomerVip;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface CustomerVipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_VIP
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Delete({
        "delete from CUSTOMER_VIP",
        "where CUST_VIP_ID = #{custVipId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long custVipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_VIP
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Insert({
        "insert into CUSTOMER_VIP (CUST_VIP_ID, CUST_ID, ",
        "VIP_GRADE, START_DATE, ",
        "END_DATAE)",
        "values (#{custVipId,jdbcType=BIGINT}, #{custId,jdbcType=BIGINT}, ",
        "#{vipGrade,jdbcType=INTEGER}, #{startDate,jdbcType=DATE}, ",
        "#{endDatae,jdbcType=DATE})"
    })
    int insert(CustomerVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_VIP
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Select({
        "select",
        "CUST_VIP_ID, CUST_ID, VIP_GRADE, START_DATE, END_DATAE",
        "from CUSTOMER_VIP",
        "where CUST_VIP_ID = #{custVipId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="CUST_VIP_ID", property="custVipId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT),
        @Result(column="VIP_GRADE", property="vipGrade", jdbcType=JdbcType.INTEGER),
        @Result(column="START_DATE", property="startDate", jdbcType=JdbcType.DATE),
        @Result(column="END_DATAE", property="endDatae", jdbcType=JdbcType.DATE)
    })
    CustomerVip selectByPrimaryKey(Long custVipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_VIP
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Select({
        "select",
        "CUST_VIP_ID, CUST_ID, VIP_GRADE, START_DATE, END_DATAE",
        "from CUSTOMER_VIP"
    })
    @Results({
        @Result(column="CUST_VIP_ID", property="custVipId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT),
        @Result(column="VIP_GRADE", property="vipGrade", jdbcType=JdbcType.INTEGER),
        @Result(column="START_DATE", property="startDate", jdbcType=JdbcType.DATE),
        @Result(column="END_DATAE", property="endDatae", jdbcType=JdbcType.DATE)
    })
    List<CustomerVip> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_VIP
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Update({
        "update CUSTOMER_VIP",
        "set CUST_ID = #{custId,jdbcType=BIGINT},",
          "VIP_GRADE = #{vipGrade,jdbcType=INTEGER},",
          "START_DATE = #{startDate,jdbcType=DATE},",
          "END_DATAE = #{endDatae,jdbcType=DATE}",
        "where CUST_VIP_ID = #{custVipId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(CustomerVip record);
}