package com.ninyjun.erp.customer.custsvc.repository;

import java.util.List;

import com.ninyjun.erp.customer.custsdk.model.Customer;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Delete({
        "delete from CUSTOMER",
        "where CUST_ID = #{custId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long custId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Insert({
        "insert into CUSTOMER (CUST_ID, CUST_NAME, ",
        "CUST_DESCRIBE, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID)",
        "values (#{custId,jdbcType=BIGINT}, #{custName,jdbcType=VARCHAR}, ",
        "#{custDescribe,jdbcType=VARCHAR}, #{createTime,jdbcType=DATE}, ",
        "#{createEmpId,jdbcType=VARCHAR}, #{createDepartId,jdbcType=VARCHAR})"
    })
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Select({
        "select",
        "CUST_ID, CUST_NAME, CUST_DESCRIBE, CREATE_TIME, CREATE_EMP_ID, CREATE_DEPART_ID",
        "from CUSTOMER",
        "where CUST_ID = #{custId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CUST_NAME", property="custName", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUST_DESCRIBE", property="custDescribe", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    Customer selectByPrimaryKey(Long custId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Select({
        "select",
        "CUST_ID, CUST_NAME, CUST_DESCRIBE, CREATE_TIME, CREATE_EMP_ID, CREATE_DEPART_ID",
        "from CUSTOMER"
    })
    @Results({
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CUST_NAME", property="custName", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUST_DESCRIBE", property="custDescribe", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    List<Customer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Update({
        "update CUSTOMER",
        "set CUST_NAME = #{custName,jdbcType=VARCHAR},",
          "CUST_DESCRIBE = #{custDescribe,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=DATE},",
          "CREATE_EMP_ID = #{createEmpId,jdbcType=VARCHAR},",
          "CREATE_DEPART_ID = #{createDepartId,jdbcType=VARCHAR}",
        "where CUST_ID = #{custId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Customer record);
}