package com.ninyjun.erp.customer.custsvc.repository;

import java.util.List;

import com.ninyjun.erp.customer.custsdk.model.CustomerComminfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface CustomerComminfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_COMMINFO
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Delete({
        "delete from CUSTOMER_COMMINFO",
        "where CUSTOMER_COMM_ID = #{customerCommId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long customerCommId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_COMMINFO
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Insert({
        "insert into CUSTOMER_COMMINFO (CUSTOMER_COMM_ID, CUST_ID, ",
        "COMM_TYPE, COMM_IDENTIFY)",
        "values (#{customerCommId,jdbcType=BIGINT}, #{custId,jdbcType=BIGINT}, ",
        "#{commType,jdbcType=INTEGER}, #{commIdentify,jdbcType=VARCHAR})"
    })
    int insert(CustomerComminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_COMMINFO
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Select({
        "select",
        "CUSTOMER_COMM_ID, CUST_ID, COMM_TYPE, COMM_IDENTIFY",
        "from CUSTOMER_COMMINFO",
        "where CUSTOMER_COMM_ID = #{customerCommId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="CUSTOMER_COMM_ID", property="customerCommId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT),
        @Result(column="COMM_TYPE", property="commType", jdbcType=JdbcType.INTEGER),
        @Result(column="COMM_IDENTIFY", property="commIdentify", jdbcType=JdbcType.VARCHAR)
    })
    CustomerComminfo selectByPrimaryKey(Long customerCommId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_COMMINFO
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Select({
        "select",
        "CUSTOMER_COMM_ID, CUST_ID, COMM_TYPE, COMM_IDENTIFY",
        "from CUSTOMER_COMMINFO"
    })
    @Results({
        @Result(column="CUSTOMER_COMM_ID", property="customerCommId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT),
        @Result(column="COMM_TYPE", property="commType", jdbcType=JdbcType.INTEGER),
        @Result(column="COMM_IDENTIFY", property="commIdentify", jdbcType=JdbcType.VARCHAR)
    })
    List<CustomerComminfo> selectAll();


    @Select({
            "select",
            "CUSTOMER_COMM_ID, CUST_ID, COMM_TYPE, COMM_IDENTIFY",
            "from CUSTOMER_COMMINFO",
            "where CUSTOMER_ID = #{custId,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="CUSTOMER_COMM_ID", property="customerCommId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT),
            @Result(column="COMM_TYPE", property="commType", jdbcType=JdbcType.INTEGER),
            @Result(column="COMM_IDENTIFY", property="commIdentify", jdbcType=JdbcType.VARCHAR)
    })
    List<CustomerComminfo> selectByCustId(Long custId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_COMMINFO
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Update({
        "update CUSTOMER_COMMINFO",
        "set CUST_ID = #{custId,jdbcType=BIGINT},",
          "COMM_TYPE = #{commType,jdbcType=INTEGER},",
          "COMM_IDENTIFY = #{commIdentify,jdbcType=VARCHAR}",
        "where CUSTOMER_COMM_ID = #{customerCommId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(CustomerComminfo record);
}