package com.ninyjun.erp.customer.custsvc.repository;

import java.util.List;

import com.ninyjun.erp.customer.custsdk.model.CustomerAddress;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface CustomerAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_ADDRESS
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Delete({
        "delete from CUSTOMER_ADDRESS",
        "where CUST_ADDRESS_ID = #{custAddressId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long custAddressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_ADDRESS
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Insert({
        "insert into CUSTOMER_ADDRESS (CUST_ADDRESS_ID, CUST_ID, ",
        "NATIONALITY, PROVINCE, ",
        "CITY, POST_CODE, ",
        "CUST_ADDRESS)",
        "values (#{custAddressId,jdbcType=BIGINT}, #{custId,jdbcType=BIGINT}, ",
        "#{nationality,jdbcType=VARCHAR}, #{province,jdbcType=VARCHAR}, ",
        "#{city,jdbcType=VARCHAR}, #{postCode,jdbcType=VARCHAR}, ",
        "#{custAddress,jdbcType=VARCHAR})"
    })
    int insert(CustomerAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_ADDRESS
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Select({
        "select",
        "CUST_ADDRESS_ID, CUST_ID, NATIONALITY, PROVINCE, CITY, POST_CODE, CUST_ADDRESS",
        "from CUSTOMER_ADDRESS",
        "where CUST_ADDRESS_ID = #{custAddressId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="CUST_ADDRESS_ID", property="custAddressId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT),
        @Result(column="NATIONALITY", property="nationality", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROVINCE", property="province", jdbcType=JdbcType.VARCHAR),
        @Result(column="CITY", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="POST_CODE", property="postCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUST_ADDRESS", property="custAddress", jdbcType=JdbcType.VARCHAR)
    })
    CustomerAddress selectByPrimaryKey(Long custAddressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_ADDRESS
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Select({
        "select",
        "CUST_ADDRESS_ID, CUST_ID, NATIONALITY, PROVINCE, CITY, POST_CODE, CUST_ADDRESS",
        "from CUSTOMER_ADDRESS"
    })
    @Results({
        @Result(column="CUST_ADDRESS_ID", property="custAddressId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT),
        @Result(column="NATIONALITY", property="nationality", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROVINCE", property="province", jdbcType=JdbcType.VARCHAR),
        @Result(column="CITY", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="POST_CODE", property="postCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUST_ADDRESS", property="custAddress", jdbcType=JdbcType.VARCHAR)
    })
    List<CustomerAddress> selectAll();

    @Select({
            "select",
            "CUST_ADDRESS_ID, CUST_ID, NATIONALITY, PROVINCE, CITY, POST_CODE, CUST_ADDRESS",
            "from CUSTOMER_ADDRESS",
            " where CUST_ID = #{custId,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="CUST_ADDRESS_ID", property="custAddressId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT),
            @Result(column="NATIONALITY", property="nationality", jdbcType=JdbcType.VARCHAR),
            @Result(column="PROVINCE", property="province", jdbcType=JdbcType.VARCHAR),
            @Result(column="CITY", property="city", jdbcType=JdbcType.VARCHAR),
            @Result(column="POST_CODE", property="postCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="CUST_ADDRESS", property="custAddress", jdbcType=JdbcType.VARCHAR)
    })
    List<CustomerAddress> selectByCustId(Long custId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_ADDRESS
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Update({
        "update CUSTOMER_ADDRESS",
        "set CUST_ID = #{custId,jdbcType=BIGINT},",
          "NATIONALITY = #{nationality,jdbcType=VARCHAR},",
          "PROVINCE = #{province,jdbcType=VARCHAR},",
          "CITY = #{city,jdbcType=VARCHAR},",
          "POST_CODE = #{postCode,jdbcType=VARCHAR},",
          "CUST_ADDRESS = #{custAddress,jdbcType=VARCHAR}",
        "where CUST_ADDRESS_ID = #{custAddressId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(CustomerAddress record);
}