package com.ninyjun.erp.customer.custsvc.repository;

import java.util.List;

import com.ninyjun.erp.customer.custsdk.model.CustomerExtra;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface CustomerExtraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_EXTRA
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Delete({
        "delete from CUSTOMER_EXTRA",
        "where CUST_ID = #{custId,jdbcType=BIGINT}",
          "and PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("custId") Long custId, @Param("propertyCode") String propertyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_EXTRA
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Insert({
        "insert into CUSTOMER_EXTRA (CUST_ID, PROPERTY_CODE, ",
        "PROPERTY_VALUE)",
        "values (#{custId,jdbcType=BIGINT}, #{propertyCode,jdbcType=VARCHAR}, ",
        "#{propertyValue,jdbcType=VARCHAR})"
    })
    int insert(CustomerExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_EXTRA
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Select({
        "select",
        "CUST_ID, PROPERTY_CODE, PROPERTY_VALUE",
        "from CUSTOMER_EXTRA",
        "where CUST_ID = #{custId,jdbcType=BIGINT}",
          "and PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="PROPERTY_CODE", property="propertyCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PROPERTY_VALUE", property="propertyValue", jdbcType=JdbcType.VARCHAR)
    })
    CustomerExtra selectByPrimaryKey(@Param("custId") Long custId, @Param("propertyCode") String propertyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_EXTRA
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Select({
        "select",
        "CUST_ID, PROPERTY_CODE, PROPERTY_VALUE",
        "from CUSTOMER_EXTRA"
    })
    @Results({
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="PROPERTY_CODE", property="propertyCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PROPERTY_VALUE", property="propertyValue", jdbcType=JdbcType.VARCHAR)
    })
    List<CustomerExtra> selectAll();


    @Select({
            "select",
            "CUST_ID, PROPERTY_CODE, PROPERTY_VALUE",
            "from CUSTOMER_EXTRA",
            "where CUST_ID = #{custId,jdbcType=BIGINT}",
    })
    @Results({
            @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="PROPERTY_CODE", property="propertyCode", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="PROPERTY_VALUE", property="propertyValue", jdbcType=JdbcType.VARCHAR)
    })
    List<CustomerExtra> selectByCustId(Long custId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER_EXTRA
     *
     * @mbg.generated Thu Nov 28 20:38:37 CST 2019
     */
    @Update({
        "update CUSTOMER_EXTRA",
        "set PROPERTY_VALUE = #{propertyValue,jdbcType=VARCHAR}",
        "where CUST_ID = #{custId,jdbcType=BIGINT}",
          "and PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(CustomerExtra record);
}