package com.ninyjun.erp.order.salesvc.repository;

import java.util.List;

import com.ninyjun.erp.order.ordersdk.model.SaleCancel;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface SaleCancelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_CANCEL
     *
     * @mbg.generated Thu Nov 28 20:54:51 CST 2019
     */
    @Delete({
        "delete from SALE_CANCEL",
        "where SALE_ID = #{saleId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long saleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_CANCEL
     *
     * @mbg.generated Thu Nov 28 20:54:51 CST 2019
     */
    @Insert({
        "insert into SALE_CANCEL (SALE_ID, SALE_ID_NEW, ",
        "CANCEL_TAG, REASON_CODE, ",
        "CANCEL_DESCRIBE, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID)",
        "values (#{saleId,jdbcType=BIGINT}, #{saleIdNew,jdbcType=BIGINT}, ",
        "#{cancelTag,jdbcType=INTEGER}, #{reasonCode,jdbcType=INTEGER}, ",
        "#{cancelDescribe,jdbcType=VARCHAR}, #{createTime,jdbcType=DATE}, ",
        "#{createEmpId,jdbcType=VARCHAR}, #{createDepartId,jdbcType=VARCHAR})"
    })
    int insert(SaleCancel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_CANCEL
     *
     * @mbg.generated Thu Nov 28 20:54:51 CST 2019
     */
    @Select({
        "select",
        "SALE_ID, SALE_ID_NEW, CANCEL_TAG, REASON_CODE, CANCEL_DESCRIBE, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID",
        "from SALE_CANCEL",
        "where SALE_ID = #{saleId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="SALE_ID", property="saleId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="SALE_ID_NEW", property="saleIdNew", jdbcType=JdbcType.BIGINT),
        @Result(column="CANCEL_TAG", property="cancelTag", jdbcType=JdbcType.INTEGER),
        @Result(column="REASON_CODE", property="reasonCode", jdbcType=JdbcType.INTEGER),
        @Result(column="CANCEL_DESCRIBE", property="cancelDescribe", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    SaleCancel selectByPrimaryKey(Long saleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_CANCEL
     *
     * @mbg.generated Thu Nov 28 20:54:51 CST 2019
     */
    @Select({
        "select",
        "SALE_ID, SALE_ID_NEW, CANCEL_TAG, REASON_CODE, CANCEL_DESCRIBE, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID",
        "from SALE_CANCEL"
    })
    @Results({
        @Result(column="SALE_ID", property="saleId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="SALE_ID_NEW", property="saleIdNew", jdbcType=JdbcType.BIGINT),
        @Result(column="CANCEL_TAG", property="cancelTag", jdbcType=JdbcType.INTEGER),
        @Result(column="REASON_CODE", property="reasonCode", jdbcType=JdbcType.INTEGER),
        @Result(column="CANCEL_DESCRIBE", property="cancelDescribe", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    List<SaleCancel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_CANCEL
     *
     * @mbg.generated Thu Nov 28 20:54:51 CST 2019
     */
    @Update({
        "update SALE_CANCEL",
        "set SALE_ID_NEW = #{saleIdNew,jdbcType=BIGINT},",
          "CANCEL_TAG = #{cancelTag,jdbcType=INTEGER},",
          "REASON_CODE = #{reasonCode,jdbcType=INTEGER},",
          "CANCEL_DESCRIBE = #{cancelDescribe,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=DATE},",
          "CREATE_EMP_ID = #{createEmpId,jdbcType=VARCHAR},",
          "CREATE_DEPART_ID = #{createDepartId,jdbcType=VARCHAR}",
        "where SALE_ID = #{saleId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SaleCancel record);
}