package com.ninyjun.erp.order.salesvc.repository;

import java.util.List;

import com.ninyjun.erp.order.ordersdk.model.SaleDetail;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface SaleDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_DETAIL
     *
     * @mbg.generated Thu Nov 28 20:54:51 CST 2019
     */
    @Delete({
        "delete from SALE_DETAIL",
        "where SALE_DETAIL_ID = #{saleDetailId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long saleDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_DETAIL
     *
     * @mbg.generated Thu Nov 28 20:54:51 CST 2019
     */
    @Insert({
        "insert into SALE_DETAIL (SALE_DETAIL_ID, SALE_ID, ",
        "INVENTORY_ID, PRODUCT_CODE, ",
        "BATCH_NO, PRICE, ",
        "QUANTITY, DISCOUNT, ",
        "INVENTORY_OUTIN_ID)",
        "values (#{saleDetailId,jdbcType=BIGINT}, #{saleId,jdbcType=BIGINT}, ",
        "#{inventoryId,jdbcType=BIGINT}, #{productCode,jdbcType=INTEGER}, ",
        "#{batchNo,jdbcType=VARCHAR}, #{price,jdbcType=INTEGER}, ",
        "#{quantity,jdbcType=INTEGER}, #{discount,jdbcType=INTEGER}, ",
        "#{inventoryOutinId,jdbcType=BIGINT})"
    })
    int insert(SaleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_DETAIL
     *
     * @mbg.generated Thu Nov 28 20:54:51 CST 2019
     */
    @Select({
        "select",
        "SALE_DETAIL_ID, SALE_ID, INVENTORY_ID, PRODUCT_CODE, BATCH_NO, PRICE, QUANTITY, ",
        "DISCOUNT, INVENTORY_OUTIN_ID",
        "from SALE_DETAIL",
        "where SALE_DETAIL_ID = #{saleDetailId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="SALE_DETAIL_ID", property="saleDetailId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="SALE_ID", property="saleId", jdbcType=JdbcType.BIGINT),
        @Result(column="INVENTORY_ID", property="inventoryId", jdbcType=JdbcType.BIGINT),
        @Result(column="PRODUCT_CODE", property="productCode", jdbcType=JdbcType.INTEGER),
        @Result(column="BATCH_NO", property="batchNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRICE", property="price", jdbcType=JdbcType.INTEGER),
        @Result(column="QUANTITY", property="quantity", jdbcType=JdbcType.INTEGER),
        @Result(column="DISCOUNT", property="discount", jdbcType=JdbcType.INTEGER),
        @Result(column="INVENTORY_OUTIN_ID", property="inventoryOutinId", jdbcType=JdbcType.BIGINT)
    })
    SaleDetail selectByPrimaryKey(Long saleDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_DETAIL
     *
     * @mbg.generated Thu Nov 28 20:54:51 CST 2019
     */
    @Select({
        "select",
        "SALE_DETAIL_ID, SALE_ID, INVENTORY_ID, PRODUCT_CODE, BATCH_NO, PRICE, QUANTITY, ",
        "DISCOUNT, INVENTORY_OUTIN_ID",
        "from SALE_DETAIL"
    })
    @Results({
        @Result(column="SALE_DETAIL_ID", property="saleDetailId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="SALE_ID", property="saleId", jdbcType=JdbcType.BIGINT),
        @Result(column="INVENTORY_ID", property="inventoryId", jdbcType=JdbcType.BIGINT),
        @Result(column="PRODUCT_CODE", property="productCode", jdbcType=JdbcType.INTEGER),
        @Result(column="BATCH_NO", property="batchNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRICE", property="price", jdbcType=JdbcType.INTEGER),
        @Result(column="QUANTITY", property="quantity", jdbcType=JdbcType.INTEGER),
        @Result(column="DISCOUNT", property="discount", jdbcType=JdbcType.INTEGER),
        @Result(column="INVENTORY_OUTIN_ID", property="inventoryOutinId", jdbcType=JdbcType.BIGINT)
    })
    List<SaleDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_DETAIL
     *
     * @mbg.generated Thu Nov 28 20:54:51 CST 2019
     */
    @Update({
        "update SALE_DETAIL",
        "set SALE_ID = #{saleId,jdbcType=BIGINT},",
          "INVENTORY_ID = #{inventoryId,jdbcType=BIGINT},",
          "PRODUCT_CODE = #{productCode,jdbcType=INTEGER},",
          "BATCH_NO = #{batchNo,jdbcType=VARCHAR},",
          "PRICE = #{price,jdbcType=INTEGER},",
          "QUANTITY = #{quantity,jdbcType=INTEGER},",
          "DISCOUNT = #{discount,jdbcType=INTEGER},",
          "INVENTORY_OUTIN_ID = #{inventoryOutinId,jdbcType=BIGINT}",
        "where SALE_DETAIL_ID = #{saleDetailId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SaleDetail record);
}