package com.ninyjun.erp.order.salesvc.repository;

import java.util.List;

import com.ninyjun.erp.order.ordersdk.model.Sale;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface SaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE
     *
     * @mbg.generated Thu Nov 28 20:54:51 CST 2019
     */
    @Delete({
        "delete from SALE",
        "where SALE_ID = #{saleId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long saleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE
     *
     * @mbg.generated Thu Nov 28 20:54:51 CST 2019
     */
    @Insert({
        "insert into SALE (SALE_ID, CUST_ID, ",
        "ACCT_ID, RECV_FEE, CHARGE_FEE, ",
        "CHECKOUT, SETTLE_ACCOUNT, ",
        "CREATE_TIME, CREATE_EMP_ID, ",
        "CREATE_DEPART_ID)",
        "values (#{saleId,jdbcType=BIGINT}, #{custId,jdbcType=BIGINT}, ",
        "#{acctId,jdbcType=BIGINT}, #{recvFee,jdbcType=BIGINT}, #{chargeFee,jdbcType=BIGINT}, ",
        "#{checkout,jdbcType=INTEGER}, #{settleAccount,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=DATE}, #{createEmpId,jdbcType=VARCHAR}, ",
        "#{createDepartId,jdbcType=VARCHAR})"
    })
    int insert(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE
     *
     * @mbg.generated Thu Nov 28 20:54:51 CST 2019
     */
    @Select({
        "select",
        "SALE_ID, CUST_ID, ACCT_ID, RECV_FEE, CHARGE_FEE, CHECKOUT, SETTLE_ACCOUNT, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID",
        "from SALE",
        "where SALE_ID = #{saleId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="SALE_ID", property="saleId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT),
        @Result(column="ACCT_ID", property="acctId", jdbcType=JdbcType.BIGINT),
        @Result(column="RECV_FEE", property="recvFee", jdbcType=JdbcType.BIGINT),
        @Result(column="CHARGE_FEE", property="chargeFee", jdbcType=JdbcType.BIGINT),
        @Result(column="CHECKOUT", property="checkout", jdbcType=JdbcType.INTEGER),
        @Result(column="SETTLE_ACCOUNT", property="settleAccount", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    Sale selectByPrimaryKey(Long saleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE
     *
     * @mbg.generated Thu Nov 28 20:54:51 CST 2019
     */
    @Select({
        "select",
        "SALE_ID, CUST_ID, ACCT_ID, RECV_FEE, CHARGE_FEE, CHECKOUT, SETTLE_ACCOUNT, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID",
        "from SALE"
    })
    @Results({
        @Result(column="SALE_ID", property="saleId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.BIGINT),
        @Result(column="ACCT_ID", property="acctId", jdbcType=JdbcType.BIGINT),
        @Result(column="RECV_FEE", property="recvFee", jdbcType=JdbcType.BIGINT),
        @Result(column="CHARGE_FEE", property="chargeFee", jdbcType=JdbcType.BIGINT),
        @Result(column="CHECKOUT", property="checkout", jdbcType=JdbcType.INTEGER),
        @Result(column="SETTLE_ACCOUNT", property="settleAccount", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    List<Sale> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE
     *
     * @mbg.generated Thu Nov 28 20:54:51 CST 2019
     */
    @Update({
        "update SALE",
        "set CUST_ID = #{custId,jdbcType=BIGINT},",
          "ACCT_ID = #{acctId,jdbcType=BIGINT},",
          "RECV_FEE = #{recvFee,jdbcType=BIGINT},",
          "CHARGE_FEE = #{chargeFee,jdbcType=BIGINT},",
          "CHECKOUT = #{checkout,jdbcType=INTEGER},",
          "SETTLE_ACCOUNT = #{settleAccount,jdbcType=INTEGER},",
          "CREATE_TIME = #{createTime,jdbcType=DATE},",
          "CREATE_EMP_ID = #{createEmpId,jdbcType=VARCHAR},",
          "CREATE_DEPART_ID = #{createDepartId,jdbcType=VARCHAR}",
        "where SALE_ID = #{saleId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Sale record);
}