package com.ninyjun.erp.product.prodsvc.repository;

import com.ninyjun.erp.product.prodsvc.model.Product;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Delete({
        "delete from PRODUCT",
        "where PRODUCT_CODE = #{productCode,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer productCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Insert({
        "insert into PRODUCT (PRODUCT_CODE, PRODUCT_NAME, ",
        "PRODUCT_PYM, PRODUCT_SPEC, ",
        "PROD_CATALOG_CODE, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID)",
        "values (#{productCode,jdbcType=INTEGER}, #{productName,jdbcType=VARCHAR}, ",
        "#{productPym,jdbcType=VARCHAR}, #{productSpec,jdbcType=VARCHAR}, ",
        "#{prodCatalogCode,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{createEmpId,jdbcType=VARCHAR}, #{createDepartId,jdbcType=VARCHAR})"
    })
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Select({
        "select",
        "PRODUCT_CODE, PRODUCT_NAME, PRODUCT_PYM, PRODUCT_SPEC, PROD_CATALOG_CODE, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID",
        "from PRODUCT",
        "where PRODUCT_CODE = #{productCode,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="PRODUCT_CODE", property="productCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="PRODUCT_NAME", property="productName", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRODUCT_PYM", property="productPym", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRODUCT_SPEC", property="productSpec", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROD_CATALOG_CODE", property="prodCatalogCode", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    Product selectByPrimaryKey(Integer productCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Select({
        "select",
        "PRODUCT_CODE, PRODUCT_NAME, PRODUCT_PYM, PRODUCT_SPEC, PROD_CATALOG_CODE, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID",
        "from PRODUCT"
    })
    @Results({
        @Result(column="PRODUCT_CODE", property="productCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="PRODUCT_NAME", property="productName", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRODUCT_PYM", property="productPym", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRODUCT_SPEC", property="productSpec", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROD_CATALOG_CODE", property="prodCatalogCode", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    List<Product> selectAll();


    @Select({
            "select",
            "PRODUCT_CODE, PRODUCT_NAME, PRODUCT_PYM, PRODUCT_SPEC, PROD_CATALOG_CODE, CREATE_TIME, ",
            "CREATE_EMP_ID, CREATE_DEPART_ID",
            "from PRODUCT where PRODUCT_PYM like #{productPym,jdbcType=VARCHAR} limit #{limitNum,jdbcType=INTEGER} "
    })
    @Results({
            @Result(column="PRODUCT_CODE", property="productCode", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="PRODUCT_NAME", property="productName", jdbcType=JdbcType.VARCHAR),
            @Result(column="PRODUCT_PYM", property="productPym", jdbcType=JdbcType.VARCHAR),
            @Result(column="PRODUCT_SPEC", property="productSpec", jdbcType=JdbcType.VARCHAR),
            @Result(column="PROD_CATALOG_CODE", property="prodCatalogCode", jdbcType=JdbcType.INTEGER),
            @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
            @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    List<Product> selectMatchPym(String productPym,Integer limitNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Update({
        "update PRODUCT",
        "set PRODUCT_NAME = #{productName,jdbcType=VARCHAR},",
          "PRODUCT_PYM = #{productPym,jdbcType=VARCHAR},",
          "PRODUCT_SPEC = #{productSpec,jdbcType=VARCHAR},",
          "PROD_CATALOG_CODE = #{prodCatalogCode,jdbcType=INTEGER},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "CREATE_EMP_ID = #{createEmpId,jdbcType=VARCHAR},",
          "CREATE_DEPART_ID = #{createDepartId,jdbcType=VARCHAR}",
        "where PRODUCT_CODE = #{productCode,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Product record);
}