package com.ninyjun.erp.product.prodsvc.repository;

import com.ninyjun.erp.product.prodsvc.model.ProductCompose;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface ProductComposeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMPOSE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Delete({
        "delete from PRODUCT_COMPOSE",
        "where PRODUCT_CODE = #{productCode,jdbcType=INTEGER}",
          "and PRODUCT_CODE_COMP = #{productCodeComp,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("productCode") Integer productCode, @Param("productCodeComp") Integer productCodeComp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMPOSE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Insert({
        "insert into PRODUCT_COMPOSE (PRODUCT_CODE, PRODUCT_CODE_COMP)",
        "values (#{productCode,jdbcType=INTEGER}, #{productCodeComp,jdbcType=INTEGER})"
    })
    int insert(ProductCompose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMPOSE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Select({
        "select",
        "PRODUCT_CODE, PRODUCT_CODE_COMP",
        "from PRODUCT_COMPOSE"
    })
    @Results({
        @Result(column="PRODUCT_CODE", property="productCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="PRODUCT_CODE_COMP", property="productCodeComp", jdbcType=JdbcType.INTEGER, id=true)
    })
    List<ProductCompose> selectAll();
}