package com.ninyjun.erp.product.prodsvc.repository;

import com.ninyjun.erp.product.prodsvc.model.ProductExtra;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ProductExtraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_EXTRA
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Delete({
        "delete from PRODUCT_EXTRA",
        "where PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR}",
          "and PRODUCT_CODE = #{productCode,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("propertyCode") String propertyCode, @Param("productCode") Integer productCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_EXTRA
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Insert({
        "insert into PRODUCT_EXTRA (PROPERTY_CODE, PRODUCT_CODE, ",
        "PROPERTY_VALUE)",
        "values (#{propertyCode,jdbcType=VARCHAR}, #{productCode,jdbcType=INTEGER}, ",
        "#{propertyValue,jdbcType=VARCHAR})"
    })
    int insert(ProductExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_EXTRA
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Select({
        "select",
        "PROPERTY_CODE, PRODUCT_CODE, PROPERTY_VALUE",
        "from PRODUCT_EXTRA",
        "where PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR}",
          "and PRODUCT_CODE = #{productCode,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="PROPERTY_CODE", property="propertyCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PRODUCT_CODE", property="productCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="PROPERTY_VALUE", property="propertyValue", jdbcType=JdbcType.VARCHAR)
    })
    ProductExtra selectByPrimaryKey(@Param("propertyCode") String propertyCode, @Param("productCode") Integer productCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_EXTRA
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Select({
        "select",
        "PROPERTY_CODE, PRODUCT_CODE, PROPERTY_VALUE",
        "from PRODUCT_EXTRA"
    })
    @Results({
        @Result(column="PROPERTY_CODE", property="propertyCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PRODUCT_CODE", property="productCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="PROPERTY_VALUE", property="propertyValue", jdbcType=JdbcType.VARCHAR)
    })
    List<ProductExtra> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_EXTRA
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Update({
        "update PRODUCT_EXTRA",
        "set PROPERTY_VALUE = #{propertyValue,jdbcType=VARCHAR}",
        "where PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR}",
          "and PRODUCT_CODE = #{productCode,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ProductExtra record);
}