package com.ninyjun.erp.product.prodsvc.repository;

import com.ninyjun.erp.product.prodsvc.model.ProductSpectacleFrame;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ProductSpectacleFrameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SPECTACLE_FRAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Delete({
        "delete from PRODUCT_SPECTACLE_FRAME",
        "where SPECTACLE_FRAME_CODE = #{spectacleFrameCode,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer spectacleFrameCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SPECTACLE_FRAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Insert({
        "insert into PRODUCT_SPECTACLE_FRAME (SPECTACLE_FRAME_CODE, SPECTACLE_FRAME_NAME, ",
        "SPECTACLE_FRAME_PYM, SPEC)",
        "values (#{spectacleFrameCode,jdbcType=INTEGER}, #{spectacleFrameName,jdbcType=VARCHAR}, ",
        "#{spectacleFramePym,jdbcType=VARCHAR}, #{spec,jdbcType=VARCHAR})"
    })
    int insert(ProductSpectacleFrame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SPECTACLE_FRAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Select({
        "select",
        "SPECTACLE_FRAME_CODE, SPECTACLE_FRAME_NAME, SPECTACLE_FRAME_PYM, SPEC",
        "from PRODUCT_SPECTACLE_FRAME",
        "where SPECTACLE_FRAME_CODE = #{spectacleFrameCode,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="SPECTACLE_FRAME_CODE", property="spectacleFrameCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="SPECTACLE_FRAME_NAME", property="spectacleFrameName", jdbcType=JdbcType.VARCHAR),
        @Result(column="SPECTACLE_FRAME_PYM", property="spectacleFramePym", jdbcType=JdbcType.VARCHAR),
        @Result(column="SPEC", property="spec", jdbcType=JdbcType.VARCHAR)
    })
    ProductSpectacleFrame selectByPrimaryKey(Integer spectacleFrameCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SPECTACLE_FRAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Select({
        "select",
        "SPECTACLE_FRAME_CODE, SPECTACLE_FRAME_NAME, SPECTACLE_FRAME_PYM, SPEC",
        "from PRODUCT_SPECTACLE_FRAME"
    })
    @Results({
        @Result(column="SPECTACLE_FRAME_CODE", property="spectacleFrameCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="SPECTACLE_FRAME_NAME", property="spectacleFrameName", jdbcType=JdbcType.VARCHAR),
        @Result(column="SPECTACLE_FRAME_PYM", property="spectacleFramePym", jdbcType=JdbcType.VARCHAR),
        @Result(column="SPEC", property="spec", jdbcType=JdbcType.VARCHAR)
    })
    List<ProductSpectacleFrame> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SPECTACLE_FRAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Update({
        "update PRODUCT_SPECTACLE_FRAME",
        "set SPECTACLE_FRAME_NAME = #{spectacleFrameName,jdbcType=VARCHAR},",
          "SPECTACLE_FRAME_PYM = #{spectacleFramePym,jdbcType=VARCHAR},",
          "SPEC = #{spec,jdbcType=VARCHAR}",
        "where SPECTACLE_FRAME_CODE = #{spectacleFrameCode,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ProductSpectacleFrame record);
}