package com.ninyjun.erp.product.prodsvc.repository;

import com.ninyjun.erp.product.prodsvc.model.ProductOptic;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ProductOpticMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_OPTIC
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Delete({
        "delete from PRODUCT_OPTIC",
        "where OPTIC_CODE = #{opticCode,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer opticCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_OPTIC
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Insert({
        "insert into PRODUCT_OPTIC (OPTIC_CODE, OPTIC_NAME, ",
        "OPTIC_PYM, OPTIC_SPEC)",
        "values (#{opticCode,jdbcType=INTEGER}, #{opticName,jdbcType=VARCHAR}, ",
        "#{opticPym,jdbcType=VARCHAR}, #{opticSpec,jdbcType=VARCHAR})"
    })
    int insert(ProductOptic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_OPTIC
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Select({
        "select",
        "OPTIC_CODE, OPTIC_NAME, OPTIC_PYM, OPTIC_SPEC",
        "from PRODUCT_OPTIC",
        "where OPTIC_CODE = #{opticCode,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="OPTIC_CODE", property="opticCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="OPTIC_NAME", property="opticName", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPTIC_PYM", property="opticPym", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPTIC_SPEC", property="opticSpec", jdbcType=JdbcType.VARCHAR)
    })
    ProductOptic selectByPrimaryKey(Integer opticCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_OPTIC
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Select({
        "select",
        "OPTIC_CODE, OPTIC_NAME, OPTIC_PYM, OPTIC_SPEC",
        "from PRODUCT_OPTIC"
    })
    @Results({
        @Result(column="OPTIC_CODE", property="opticCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="OPTIC_NAME", property="opticName", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPTIC_PYM", property="opticPym", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPTIC_SPEC", property="opticSpec", jdbcType=JdbcType.VARCHAR)
    })
    List<ProductOptic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_OPTIC
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Update({
        "update PRODUCT_OPTIC",
        "set OPTIC_NAME = #{opticName,jdbcType=VARCHAR},",
          "OPTIC_PYM = #{opticPym,jdbcType=VARCHAR},",
          "OPTIC_SPEC = #{opticSpec,jdbcType=VARCHAR}",
        "where OPTIC_CODE = #{opticCode,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ProductOptic record);
}