package com.ninyjun.erp.product.prodsvc.repository;

import com.ninyjun.erp.product.prodsvc.model.ProductPrice;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ProductPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PRICE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Delete({
        "delete from PRODUCT_PRICE",
        "where PRODUCT_CODE = #{productCode,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer productCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PRICE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Insert({
        "insert into PRODUCT_PRICE (PRODUCT_CODE, PRODUCT_PRICE)",
        "values (#{productCode,jdbcType=INTEGER}, #{productPrice,jdbcType=INTEGER})"
    })
    int insert(ProductPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PRICE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Select({
        "select",
        "PRODUCT_CODE, PRODUCT_PRICE",
        "from PRODUCT_PRICE",
        "where PRODUCT_CODE = #{productCode,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="PRODUCT_CODE", property="productCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="PRODUCT_PRICE", property="productPrice", jdbcType=JdbcType.INTEGER)
    })
    ProductPrice selectByPrimaryKey(Integer productCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PRICE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Select({
        "select",
        "PRODUCT_CODE, PRODUCT_PRICE",
        "from PRODUCT_PRICE"
    })
    @Results({
        @Result(column="PRODUCT_CODE", property="productCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="PRODUCT_PRICE", property="productPrice", jdbcType=JdbcType.INTEGER)
    })
    List<ProductPrice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PRICE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Update({
        "update PRODUCT_PRICE",
        "set PRODUCT_PRICE = #{productPrice,jdbcType=INTEGER}",
        "where PRODUCT_CODE = #{productCode,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ProductPrice record);
}