package com.ninyjun.erp.product.prodsvc.repository;

import com.ninyjun.erp.product.prodsvc.model.ProductServiceItem;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ProductServiceItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SERVICE_ITEM
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Delete({
        "delete from PRODUCT_SERVICE_ITEM",
        "where SERVICE_ITEM_CODE = #{serviceItemCode,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer serviceItemCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SERVICE_ITEM
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Insert({
        "insert into PRODUCT_SERVICE_ITEM (SERVICE_ITEM_CODE, SERVICE_ITEM_NAME)",
        "values (#{serviceItemCode,jdbcType=INTEGER}, #{serviceItemName,jdbcType=VARCHAR})"
    })
    int insert(ProductServiceItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SERVICE_ITEM
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Select({
        "select",
        "SERVICE_ITEM_CODE, SERVICE_ITEM_NAME",
        "from PRODUCT_SERVICE_ITEM",
        "where SERVICE_ITEM_CODE = #{serviceItemCode,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="SERVICE_ITEM_CODE", property="serviceItemCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="SERVICE_ITEM_NAME", property="serviceItemName", jdbcType=JdbcType.VARCHAR)
    })
    ProductServiceItem selectByPrimaryKey(Integer serviceItemCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SERVICE_ITEM
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Select({
        "select",
        "SERVICE_ITEM_CODE, SERVICE_ITEM_NAME",
        "from PRODUCT_SERVICE_ITEM"
    })
    @Results({
        @Result(column="SERVICE_ITEM_CODE", property="serviceItemCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="SERVICE_ITEM_NAME", property="serviceItemName", jdbcType=JdbcType.VARCHAR)
    })
    List<ProductServiceItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SERVICE_ITEM
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @Update({
        "update PRODUCT_SERVICE_ITEM",
        "set SERVICE_ITEM_NAME = #{serviceItemName,jdbcType=VARCHAR}",
        "where SERVICE_ITEM_CODE = #{serviceItemCode,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ProductServiceItem record);
}