package com.ninyjun.erp.product.prodsvc.model;

public class ProductServiceItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SERVICE_ITEM.SERVICE_ITEM_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private Integer serviceItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SERVICE_ITEM.SERVICE_ITEM_NAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private String serviceItemName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_SERVICE_ITEM.SERVICE_ITEM_CODE
     *
     * @return the value of PRODUCT_SERVICE_ITEM.SERVICE_ITEM_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public Integer getServiceItemCode() {
        return serviceItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_SERVICE_ITEM.SERVICE_ITEM_CODE
     *
     * @param serviceItemCode the value for PRODUCT_SERVICE_ITEM.SERVICE_ITEM_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setServiceItemCode(Integer serviceItemCode) {
        this.serviceItemCode = serviceItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_SERVICE_ITEM.SERVICE_ITEM_NAME
     *
     * @return the value of PRODUCT_SERVICE_ITEM.SERVICE_ITEM_NAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public String getServiceItemName() {
        return serviceItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_SERVICE_ITEM.SERVICE_ITEM_NAME
     *
     * @param serviceItemName the value for PRODUCT_SERVICE_ITEM.SERVICE_ITEM_NAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setServiceItemName(String serviceItemName) {
        this.serviceItemName = serviceItemName == null ? null : serviceItemName.trim();
    }
}