package com.ninyjun.erp.product.prodsvc.model;

import java.util.Date;

public class ProductCatalog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_CATALOG.PROD_CATALOG_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private Integer prodCatalogCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_CATALOG.PROD_CATALOG_NAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private String prodCatalogName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_CATALOG.PROD_CATALOG_DESCRIBE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private String prodCatalogDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_CATALOG.PROD_CATALOG_UP
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private Integer prodCatalogUp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_CATALOG.PROD_LEVEL
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private Integer prodLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_CATALOG.CREATE_TIME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_CATALOG.CREATE_EMP_ID
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private String createEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_CATALOG.CREATE_DEPART_ID
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private String createDepartId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_CATALOG.PROD_CATALOG_CODE
     *
     * @return the value of PRODUCT_CATALOG.PROD_CATALOG_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public Integer getProdCatalogCode() {
        return prodCatalogCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_CATALOG.PROD_CATALOG_CODE
     *
     * @param prodCatalogCode the value for PRODUCT_CATALOG.PROD_CATALOG_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setProdCatalogCode(Integer prodCatalogCode) {
        this.prodCatalogCode = prodCatalogCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_CATALOG.PROD_CATALOG_NAME
     *
     * @return the value of PRODUCT_CATALOG.PROD_CATALOG_NAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public String getProdCatalogName() {
        return prodCatalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_CATALOG.PROD_CATALOG_NAME
     *
     * @param prodCatalogName the value for PRODUCT_CATALOG.PROD_CATALOG_NAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setProdCatalogName(String prodCatalogName) {
        this.prodCatalogName = prodCatalogName == null ? null : prodCatalogName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_CATALOG.PROD_CATALOG_DESCRIBE
     *
     * @return the value of PRODUCT_CATALOG.PROD_CATALOG_DESCRIBE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public String getProdCatalogDescribe() {
        return prodCatalogDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_CATALOG.PROD_CATALOG_DESCRIBE
     *
     * @param prodCatalogDescribe the value for PRODUCT_CATALOG.PROD_CATALOG_DESCRIBE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setProdCatalogDescribe(String prodCatalogDescribe) {
        this.prodCatalogDescribe = prodCatalogDescribe == null ? null : prodCatalogDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_CATALOG.PROD_CATALOG_UP
     *
     * @return the value of PRODUCT_CATALOG.PROD_CATALOG_UP
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public Integer getProdCatalogUp() {
        return prodCatalogUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_CATALOG.PROD_CATALOG_UP
     *
     * @param prodCatalogUp the value for PRODUCT_CATALOG.PROD_CATALOG_UP
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setProdCatalogUp(Integer prodCatalogUp) {
        this.prodCatalogUp = prodCatalogUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_CATALOG.PROD_LEVEL
     *
     * @return the value of PRODUCT_CATALOG.PROD_LEVEL
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public Integer getProdLevel() {
        return prodLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_CATALOG.PROD_LEVEL
     *
     * @param prodLevel the value for PRODUCT_CATALOG.PROD_LEVEL
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setProdLevel(Integer prodLevel) {
        this.prodLevel = prodLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_CATALOG.CREATE_TIME
     *
     * @return the value of PRODUCT_CATALOG.CREATE_TIME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_CATALOG.CREATE_TIME
     *
     * @param createTime the value for PRODUCT_CATALOG.CREATE_TIME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_CATALOG.CREATE_EMP_ID
     *
     * @return the value of PRODUCT_CATALOG.CREATE_EMP_ID
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_CATALOG.CREATE_EMP_ID
     *
     * @param createEmpId the value for PRODUCT_CATALOG.CREATE_EMP_ID
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_CATALOG.CREATE_DEPART_ID
     *
     * @return the value of PRODUCT_CATALOG.CREATE_DEPART_ID
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public String getCreateDepartId() {
        return createDepartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_CATALOG.CREATE_DEPART_ID
     *
     * @param createDepartId the value for PRODUCT_CATALOG.CREATE_DEPART_ID
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setCreateDepartId(String createDepartId) {
        this.createDepartId = createDepartId == null ? null : createDepartId.trim();
    }
}