package com.ninyjun.erp.product.prodsvc.model;

public class ProductPrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_PRICE.PRODUCT_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private Integer productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_PRICE.PRODUCT_PRICE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private Integer productPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_PRICE.PRODUCT_CODE
     *
     * @return the value of PRODUCT_PRICE.PRODUCT_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public Integer getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_PRICE.PRODUCT_CODE
     *
     * @param productCode the value for PRODUCT_PRICE.PRODUCT_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setProductCode(Integer productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_PRICE.PRODUCT_PRICE
     *
     * @return the value of PRODUCT_PRICE.PRODUCT_PRICE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public Integer getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_PRICE.PRODUCT_PRICE
     *
     * @param productPrice the value for PRODUCT_PRICE.PRODUCT_PRICE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setProductPrice(Integer productPrice) {
        this.productPrice = productPrice;
    }
}