package com.ninyjun.erp.product.prodsvc.model;

public class ProductOptic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_OPTIC.OPTIC_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private Integer opticCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_OPTIC.OPTIC_NAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private String opticName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_OPTIC.OPTIC_PYM
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private String opticPym;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_OPTIC.OPTIC_SPEC
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private String opticSpec;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_OPTIC.OPTIC_CODE
     *
     * @return the value of PRODUCT_OPTIC.OPTIC_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public Integer getOpticCode() {
        return opticCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_OPTIC.OPTIC_CODE
     *
     * @param opticCode the value for PRODUCT_OPTIC.OPTIC_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setOpticCode(Integer opticCode) {
        this.opticCode = opticCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_OPTIC.OPTIC_NAME
     *
     * @return the value of PRODUCT_OPTIC.OPTIC_NAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public String getOpticName() {
        return opticName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_OPTIC.OPTIC_NAME
     *
     * @param opticName the value for PRODUCT_OPTIC.OPTIC_NAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setOpticName(String opticName) {
        this.opticName = opticName == null ? null : opticName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_OPTIC.OPTIC_PYM
     *
     * @return the value of PRODUCT_OPTIC.OPTIC_PYM
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public String getOpticPym() {
        return opticPym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_OPTIC.OPTIC_PYM
     *
     * @param opticPym the value for PRODUCT_OPTIC.OPTIC_PYM
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setOpticPym(String opticPym) {
        this.opticPym = opticPym == null ? null : opticPym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_OPTIC.OPTIC_SPEC
     *
     * @return the value of PRODUCT_OPTIC.OPTIC_SPEC
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public String getOpticSpec() {
        return opticSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_OPTIC.OPTIC_SPEC
     *
     * @param opticSpec the value for PRODUCT_OPTIC.OPTIC_SPEC
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setOpticSpec(String opticSpec) {
        this.opticSpec = opticSpec == null ? null : opticSpec.trim();
    }
}