package com.ninyjun.erp.product.prodsvc.model;

import com.alibaba.fastjson.annotation.JSONField;
import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private Integer productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_NAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_PYM
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private String productPym;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_SPEC
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private String productSpec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PROD_CATALOG_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private Integer prodCatalogCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.CREATE_TIME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */

    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.CREATE_EMP_ID
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private String createEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.CREATE_DEPART_ID
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private String createDepartId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PRODUCT_CODE
     *
     * @return the value of PRODUCT.PRODUCT_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public Integer getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PRODUCT_CODE
     *
     * @param productCode the value for PRODUCT.PRODUCT_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setProductCode(Integer productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PRODUCT_NAME
     *
     * @return the value of PRODUCT.PRODUCT_NAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PRODUCT_NAME
     *
     * @param productName the value for PRODUCT.PRODUCT_NAME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PRODUCT_PYM
     *
     * @return the value of PRODUCT.PRODUCT_PYM
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public String getProductPym() {
        return productPym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PRODUCT_PYM
     *
     * @param productPym the value for PRODUCT.PRODUCT_PYM
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setProductPym(String productPym) {
        this.productPym = productPym == null ? null : productPym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PRODUCT_SPEC
     *
     * @return the value of PRODUCT.PRODUCT_SPEC
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public String getProductSpec() {
        return productSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PRODUCT_SPEC
     *
     * @param productSpec the value for PRODUCT.PRODUCT_SPEC
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setProductSpec(String productSpec) {
        this.productSpec = productSpec == null ? null : productSpec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PROD_CATALOG_CODE
     *
     * @return the value of PRODUCT.PROD_CATALOG_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public Integer getProdCatalogCode() {
        return prodCatalogCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PROD_CATALOG_CODE
     *
     * @param prodCatalogCode the value for PRODUCT.PROD_CATALOG_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setProdCatalogCode(Integer prodCatalogCode) {
        this.prodCatalogCode = prodCatalogCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.CREATE_TIME
     *
     * @return the value of PRODUCT.CREATE_TIME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.CREATE_TIME
     *
     * @param createTime the value for PRODUCT.CREATE_TIME
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.CREATE_EMP_ID
     *
     * @return the value of PRODUCT.CREATE_EMP_ID
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.CREATE_EMP_ID
     *
     * @param createEmpId the value for PRODUCT.CREATE_EMP_ID
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.CREATE_DEPART_ID
     *
     * @return the value of PRODUCT.CREATE_DEPART_ID
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public String getCreateDepartId() {
        return createDepartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.CREATE_DEPART_ID
     *
     * @param createDepartId the value for PRODUCT.CREATE_DEPART_ID
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setCreateDepartId(String createDepartId) {
        this.createDepartId = createDepartId == null ? null : createDepartId.trim();
    }
}