package com.ninyjun.erp.product.prodsvc.model;

public class ProductCompose {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_COMPOSE.PRODUCT_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private Integer productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_COMPOSE.PRODUCT_CODE_COMP
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private Integer productCodeComp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_COMPOSE.PRODUCT_CODE
     *
     * @return the value of PRODUCT_COMPOSE.PRODUCT_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public Integer getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_COMPOSE.PRODUCT_CODE
     *
     * @param productCode the value for PRODUCT_COMPOSE.PRODUCT_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setProductCode(Integer productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_COMPOSE.PRODUCT_CODE_COMP
     *
     * @return the value of PRODUCT_COMPOSE.PRODUCT_CODE_COMP
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public Integer getProductCodeComp() {
        return productCodeComp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_COMPOSE.PRODUCT_CODE_COMP
     *
     * @param productCodeComp the value for PRODUCT_COMPOSE.PRODUCT_CODE_COMP
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setProductCodeComp(Integer productCodeComp) {
        this.productCodeComp = productCodeComp;
    }
}