package com.ninyjun.erp.product.prodsvc.model;

public class ProductExtra {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_EXTRA.PROPERTY_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private String propertyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_EXTRA.PRODUCT_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private Integer productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_EXTRA.PROPERTY_VALUE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    private String propertyValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_EXTRA.PROPERTY_CODE
     *
     * @return the value of PRODUCT_EXTRA.PROPERTY_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public String getPropertyCode() {
        return propertyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_EXTRA.PROPERTY_CODE
     *
     * @param propertyCode the value for PRODUCT_EXTRA.PROPERTY_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setPropertyCode(String propertyCode) {
        this.propertyCode = propertyCode == null ? null : propertyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_EXTRA.PRODUCT_CODE
     *
     * @return the value of PRODUCT_EXTRA.PRODUCT_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public Integer getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_EXTRA.PRODUCT_CODE
     *
     * @param productCode the value for PRODUCT_EXTRA.PRODUCT_CODE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setProductCode(Integer productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_EXTRA.PROPERTY_VALUE
     *
     * @return the value of PRODUCT_EXTRA.PROPERTY_VALUE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public String getPropertyValue() {
        return propertyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_EXTRA.PROPERTY_VALUE
     *
     * @param propertyValue the value for PRODUCT_EXTRA.PROPERTY_VALUE
     *
     * @mbg.generated Fri Nov 29 10:54:26 CST 2019
     */
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue == null ? null : propertyValue.trim();
    }
}