package com.ninyjun.erp.inventory.inventorysvc.repository;

import java.util.List;

import com.ninyjun.erp.inventory.inventorysdk.model.InventoryLoss;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface InventoryLossMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_LOSS
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Delete({
        "delete from INVENTORY_LOSS",
        "where INVENTORY_LOSS_ID = #{inventoryLossId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long inventoryLossId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_LOSS
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Insert({
        "insert into INVENTORY_LOSS (INVENTORY_LOSS_ID, INVENTORY_ID, ",
        "STOREHOUSE_CODE, LOSS_AMOUNT, ",
        "REASON_CODE, REMARK, ",
        "CREATE_TIME, CREATE_EMP_ID, ",
        "CREATE_DEPART_ID)",
        "values (#{inventoryLossId,jdbcType=BIGINT}, #{inventoryId,jdbcType=BIGINT}, ",
        "#{storehouseCode,jdbcType=INTEGER}, #{lossAmount,jdbcType=INTEGER}, ",
        "#{reasonCode,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createEmpId,jdbcType=VARCHAR}, ",
        "#{createDepartId,jdbcType=VARCHAR})"
    })
    int insert(InventoryLoss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_LOSS
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Select({
        "select",
        "INVENTORY_LOSS_ID, INVENTORY_ID, STOREHOUSE_CODE, LOSS_AMOUNT, REASON_CODE, ",
        "REMARK, CREATE_TIME, CREATE_EMP_ID, CREATE_DEPART_ID",
        "from INVENTORY_LOSS",
        "where INVENTORY_LOSS_ID = #{inventoryLossId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="INVENTORY_LOSS_ID", property="inventoryLossId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="INVENTORY_ID", property="inventoryId", jdbcType=JdbcType.BIGINT),
        @Result(column="STOREHOUSE_CODE", property="storehouseCode", jdbcType=JdbcType.INTEGER),
        @Result(column="LOSS_AMOUNT", property="lossAmount", jdbcType=JdbcType.INTEGER),
        @Result(column="REASON_CODE", property="reasonCode", jdbcType=JdbcType.INTEGER),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    InventoryLoss selectByPrimaryKey(Long inventoryLossId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_LOSS
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Select({
        "select",
        "INVENTORY_LOSS_ID, INVENTORY_ID, STOREHOUSE_CODE, LOSS_AMOUNT, REASON_CODE, ",
        "REMARK, CREATE_TIME, CREATE_EMP_ID, CREATE_DEPART_ID",
        "from INVENTORY_LOSS"
    })
    @Results({
        @Result(column="INVENTORY_LOSS_ID", property="inventoryLossId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="INVENTORY_ID", property="inventoryId", jdbcType=JdbcType.BIGINT),
        @Result(column="STOREHOUSE_CODE", property="storehouseCode", jdbcType=JdbcType.INTEGER),
        @Result(column="LOSS_AMOUNT", property="lossAmount", jdbcType=JdbcType.INTEGER),
        @Result(column="REASON_CODE", property="reasonCode", jdbcType=JdbcType.INTEGER),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    List<InventoryLoss> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_LOSS
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Update({
        "update INVENTORY_LOSS",
        "set INVENTORY_ID = #{inventoryId,jdbcType=BIGINT},",
          "STOREHOUSE_CODE = #{storehouseCode,jdbcType=INTEGER},",
          "LOSS_AMOUNT = #{lossAmount,jdbcType=INTEGER},",
          "REASON_CODE = #{reasonCode,jdbcType=INTEGER},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "CREATE_EMP_ID = #{createEmpId,jdbcType=VARCHAR},",
          "CREATE_DEPART_ID = #{createDepartId,jdbcType=VARCHAR}",
        "where INVENTORY_LOSS_ID = #{inventoryLossId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(InventoryLoss record);
}