package com.ninyjun.erp.inventory.inventorysvc.repository;

import java.util.List;

import com.ninyjun.erp.inventory.inventorysdk.model.InventoryInoutRel;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface InventoryInoutRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_INOUT_REL
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Delete({
        "delete from INVENTORY_INOUT_REL",
        "where INVENTORY_INOUT_ID = #{inventoryInoutId,jdbcType=BIGINT}",
          "and RELATION_ID = #{relationId,jdbcType=BIGINT}",
          "and TRADE_TYPE = #{tradeType,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("inventoryInoutId") Long inventoryInoutId, @Param("relationId") Long relationId, @Param("tradeType") Integer tradeType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_INOUT_REL
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Insert({
        "insert into INVENTORY_INOUT_REL (INVENTORY_INOUT_ID, RELATION_ID, ",
        "TRADE_TYPE)",
        "values (#{inventoryInoutId,jdbcType=BIGINT}, #{relationId,jdbcType=BIGINT}, ",
        "#{tradeType,jdbcType=INTEGER})"
    })
    int insert(InventoryInoutRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_INOUT_REL
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Select({
        "select",
        "INVENTORY_INOUT_ID, RELATION_ID, TRADE_TYPE",
        "from INVENTORY_INOUT_REL"
    })
    @Results({
        @Result(column="INVENTORY_INOUT_ID", property="inventoryInoutId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="RELATION_ID", property="relationId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="TRADE_TYPE", property="tradeType", jdbcType=JdbcType.INTEGER, id=true)
    })
    List<InventoryInoutRel> selectAll();
}