package com.ninyjun.erp.inventory.inventorysvc.repository;

import java.util.List;

import com.ninyjun.erp.inventory.inventorysdk.model.InventoryBatchNo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface InventoryBatchNoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_BATCH_NO
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Delete({
        "delete from INVENTORY_BATCH_NO",
        "where INVENTORY_BATCH_NO_ID = #{inventoryBatchNoId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer inventoryBatchNoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_BATCH_NO
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Insert({
        "insert into INVENTORY_BATCH_NO (INVENTORY_BATCH_NO_ID, PRODUCT_CODE, ",
        "BATCH_NO, MANUFACTURE_CODE, ",
        "PRODUCE_DATE, INVALID_DATE, ",
        "CREATE_TIME, CREATE_EMP_ID, ",
        "CREATE_DEPART_ID)",
        "values (#{inventoryBatchNoId,jdbcType=INTEGER}, #{productCode,jdbcType=INTEGER}, ",
        "#{batchNo,jdbcType=VARCHAR}, #{manufactureCode,jdbcType=INTEGER}, ",
        "#{produceDate,jdbcType=TIMESTAMP}, #{invalidDate,jdbcType=TIMESTAMP}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createEmpId,jdbcType=VARCHAR}, ",
        "#{createDepartId,jdbcType=VARCHAR})"
    })
    int insert(InventoryBatchNo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_BATCH_NO
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Select({
        "select",
        "INVENTORY_BATCH_NO_ID, PRODUCT_CODE, BATCH_NO, MANUFACTURE_CODE, PRODUCE_DATE, ",
        "INVALID_DATE, CREATE_TIME, CREATE_EMP_ID, CREATE_DEPART_ID",
        "from INVENTORY_BATCH_NO",
        "where INVENTORY_BATCH_NO_ID = #{inventoryBatchNoId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="INVENTORY_BATCH_NO_ID", property="inventoryBatchNoId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="PRODUCT_CODE", property="productCode", jdbcType=JdbcType.INTEGER),
        @Result(column="BATCH_NO", property="batchNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="MANUFACTURE_CODE", property="manufactureCode", jdbcType=JdbcType.INTEGER),
        @Result(column="PRODUCE_DATE", property="produceDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="INVALID_DATE", property="invalidDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    InventoryBatchNo selectByPrimaryKey(Integer inventoryBatchNoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_BATCH_NO
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Select({
        "select",
        "INVENTORY_BATCH_NO_ID, PRODUCT_CODE, BATCH_NO, MANUFACTURE_CODE, PRODUCE_DATE, ",
        "INVALID_DATE, CREATE_TIME, CREATE_EMP_ID, CREATE_DEPART_ID",
        "from INVENTORY_BATCH_NO"
    })
    @Results({
        @Result(column="INVENTORY_BATCH_NO_ID", property="inventoryBatchNoId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="PRODUCT_CODE", property="productCode", jdbcType=JdbcType.INTEGER),
        @Result(column="BATCH_NO", property="batchNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="MANUFACTURE_CODE", property="manufactureCode", jdbcType=JdbcType.INTEGER),
        @Result(column="PRODUCE_DATE", property="produceDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="INVALID_DATE", property="invalidDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    List<InventoryBatchNo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_BATCH_NO
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Update({
        "update INVENTORY_BATCH_NO",
        "set PRODUCT_CODE = #{productCode,jdbcType=INTEGER},",
          "BATCH_NO = #{batchNo,jdbcType=VARCHAR},",
          "MANUFACTURE_CODE = #{manufactureCode,jdbcType=INTEGER},",
          "PRODUCE_DATE = #{produceDate,jdbcType=TIMESTAMP},",
          "INVALID_DATE = #{invalidDate,jdbcType=TIMESTAMP},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "CREATE_EMP_ID = #{createEmpId,jdbcType=VARCHAR},",
          "CREATE_DEPART_ID = #{createDepartId,jdbcType=VARCHAR}",
        "where INVENTORY_BATCH_NO_ID = #{inventoryBatchNoId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(InventoryBatchNo record);
}