package com.ninyjun.erp.inventory.inventorysvc.repository;

import java.util.List;

import com.ninyjun.erp.inventory.inventorysdk.model.InventoryTransfer;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface InventoryTransferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_TRANSFER
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Delete({
        "delete from INVENTORY_TRANSFER",
        "where TRANS_ID = #{transId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long transId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_TRANSFER
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Insert({
        "insert into INVENTORY_TRANSFER (TRANS_ID, INVENTORY_ID, ",
        "TRANS_SHEETNO, AMOUNT, ",
        "CREATE_TIME, CREATE_EMP_ID, ",
        "CREATE_DEPART_ID)",
        "values (#{transId,jdbcType=BIGINT}, #{inventoryId,jdbcType=BIGINT}, ",
        "#{transSheetno,jdbcType=VARCHAR}, #{amount,jdbcType=BIGINT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createEmpId,jdbcType=VARCHAR}, ",
        "#{createDepartId,jdbcType=VARCHAR})"
    })
    int insert(InventoryTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_TRANSFER
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Select({
        "select",
        "TRANS_ID, INVENTORY_ID, TRANS_SHEETNO, AMOUNT, CREATE_TIME, CREATE_EMP_ID, CREATE_DEPART_ID",
        "from INVENTORY_TRANSFER",
        "where TRANS_ID = #{transId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="TRANS_ID", property="transId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="INVENTORY_ID", property="inventoryId", jdbcType=JdbcType.BIGINT),
        @Result(column="TRANS_SHEETNO", property="transSheetno", jdbcType=JdbcType.VARCHAR),
        @Result(column="AMOUNT", property="amount", jdbcType=JdbcType.BIGINT),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    InventoryTransfer selectByPrimaryKey(Long transId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_TRANSFER
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Select({
        "select",
        "TRANS_ID, INVENTORY_ID, TRANS_SHEETNO, AMOUNT, CREATE_TIME, CREATE_EMP_ID, CREATE_DEPART_ID",
        "from INVENTORY_TRANSFER"
    })
    @Results({
        @Result(column="TRANS_ID", property="transId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="INVENTORY_ID", property="inventoryId", jdbcType=JdbcType.BIGINT),
        @Result(column="TRANS_SHEETNO", property="transSheetno", jdbcType=JdbcType.VARCHAR),
        @Result(column="AMOUNT", property="amount", jdbcType=JdbcType.BIGINT),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    List<InventoryTransfer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_TRANSFER
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Update({
        "update INVENTORY_TRANSFER",
        "set INVENTORY_ID = #{inventoryId,jdbcType=BIGINT},",
          "TRANS_SHEETNO = #{transSheetno,jdbcType=VARCHAR},",
          "AMOUNT = #{amount,jdbcType=BIGINT},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "CREATE_EMP_ID = #{createEmpId,jdbcType=VARCHAR},",
          "CREATE_DEPART_ID = #{createDepartId,jdbcType=VARCHAR}",
        "where TRANS_ID = #{transId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(InventoryTransfer record);
}