package com.ninyjun.erp.inventory.inventorysvc.repository;

import java.util.List;

import com.ninyjun.erp.inventory.inventorysdk.model.InventoryInout;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface InventoryInoutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_INOUT
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Delete({
        "delete from INVENTORY_INOUT",
        "where INVENTORY_INOUT_ID = #{inventoryInoutId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long inventoryInoutId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_INOUT
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Insert({
        "insert into INVENTORY_INOUT (INVENTORY_INOUT_ID, INVENTORY_NO, ",
        "INOUT_TYPE, PRODUCT_CODE, ",
        "INVENTORY_BATCH_NO_ID, AMOUNT, ",
        "INVENTORY_ID, STOREHOUSE_CODE, ",
        "VERSION_NO, INVENTORY_AMOUNT, ",
        "CREATE_TIME, CREATE_EMP_ID, ",
        "CREATE_DEPART_ID)",
        "values (#{inventoryInoutId,jdbcType=BIGINT}, #{inventoryNo,jdbcType=VARCHAR}, ",
        "#{inoutType,jdbcType=INTEGER}, #{productCode,jdbcType=INTEGER}, ",
        "#{inventoryBatchNoId,jdbcType=INTEGER}, #{amount,jdbcType=BIGINT}, ",
        "#{inventoryId,jdbcType=BIGINT}, #{storehouseCode,jdbcType=INTEGER}, ",
        "#{versionNo,jdbcType=BIGINT}, #{inventoryAmount,jdbcType=BIGINT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createEmpId,jdbcType=VARCHAR}, ",
        "#{createDepartId,jdbcType=VARCHAR})"
    })
    int insert(InventoryInout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_INOUT
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Select({
        "select",
        "INVENTORY_INOUT_ID, INVENTORY_NO, INOUT_TYPE, PRODUCT_CODE, INVENTORY_BATCH_NO_ID, ",
        "AMOUNT, INVENTORY_ID, STOREHOUSE_CODE, VERSION_NO, INVENTORY_AMOUNT, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID",
        "from INVENTORY_INOUT",
        "where INVENTORY_INOUT_ID = #{inventoryInoutId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="INVENTORY_INOUT_ID", property="inventoryInoutId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="INVENTORY_NO", property="inventoryNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="INOUT_TYPE", property="inoutType", jdbcType=JdbcType.INTEGER),
        @Result(column="PRODUCT_CODE", property="productCode", jdbcType=JdbcType.INTEGER),
        @Result(column="INVENTORY_BATCH_NO_ID", property="inventoryBatchNoId", jdbcType=JdbcType.INTEGER),
        @Result(column="AMOUNT", property="amount", jdbcType=JdbcType.BIGINT),
        @Result(column="INVENTORY_ID", property="inventoryId", jdbcType=JdbcType.BIGINT),
        @Result(column="STOREHOUSE_CODE", property="storehouseCode", jdbcType=JdbcType.INTEGER),
        @Result(column="VERSION_NO", property="versionNo", jdbcType=JdbcType.BIGINT),
        @Result(column="INVENTORY_AMOUNT", property="inventoryAmount", jdbcType=JdbcType.BIGINT),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    InventoryInout selectByPrimaryKey(Long inventoryInoutId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_INOUT
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Select({
        "select",
        "INVENTORY_INOUT_ID, INVENTORY_NO, INOUT_TYPE, PRODUCT_CODE, INVENTORY_BATCH_NO_ID, ",
        "AMOUNT, INVENTORY_ID, STOREHOUSE_CODE, VERSION_NO, INVENTORY_AMOUNT, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID",
        "from INVENTORY_INOUT"
    })
    @Results({
        @Result(column="INVENTORY_INOUT_ID", property="inventoryInoutId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="INVENTORY_NO", property="inventoryNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="INOUT_TYPE", property="inoutType", jdbcType=JdbcType.INTEGER),
        @Result(column="PRODUCT_CODE", property="productCode", jdbcType=JdbcType.INTEGER),
        @Result(column="INVENTORY_BATCH_NO_ID", property="inventoryBatchNoId", jdbcType=JdbcType.INTEGER),
        @Result(column="AMOUNT", property="amount", jdbcType=JdbcType.BIGINT),
        @Result(column="INVENTORY_ID", property="inventoryId", jdbcType=JdbcType.BIGINT),
        @Result(column="STOREHOUSE_CODE", property="storehouseCode", jdbcType=JdbcType.INTEGER),
        @Result(column="VERSION_NO", property="versionNo", jdbcType=JdbcType.BIGINT),
        @Result(column="INVENTORY_AMOUNT", property="inventoryAmount", jdbcType=JdbcType.BIGINT),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    List<InventoryInout> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_INOUT
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Update({
        "update INVENTORY_INOUT",
        "set INVENTORY_NO = #{inventoryNo,jdbcType=VARCHAR},",
          "INOUT_TYPE = #{inoutType,jdbcType=INTEGER},",
          "PRODUCT_CODE = #{productCode,jdbcType=INTEGER},",
          "INVENTORY_BATCH_NO_ID = #{inventoryBatchNoId,jdbcType=INTEGER},",
          "AMOUNT = #{amount,jdbcType=BIGINT},",
          "INVENTORY_ID = #{inventoryId,jdbcType=BIGINT},",
          "STOREHOUSE_CODE = #{storehouseCode,jdbcType=INTEGER},",
          "VERSION_NO = #{versionNo,jdbcType=BIGINT},",
          "INVENTORY_AMOUNT = #{inventoryAmount,jdbcType=BIGINT},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "CREATE_EMP_ID = #{createEmpId,jdbcType=VARCHAR},",
          "CREATE_DEPART_ID = #{createDepartId,jdbcType=VARCHAR}",
        "where INVENTORY_INOUT_ID = #{inventoryInoutId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(InventoryInout record);
}