package com.ninyjun.erp.inventory.inventorysvc.repository;

import java.util.List;

import com.ninyjun.erp.inventory.inventorysdk.model.Manafacturer;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ManafacturerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MANAFACTURER
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Delete({
        "delete from MANAFACTURER",
        "where MANUFACTURE_CODE = #{manufactureCode,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer manufactureCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MANAFACTURER
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Insert({
        "insert into MANAFACTURER (MANUFACTURE_CODE, MANUFACTURE_NAME, ",
        "MANUFACTURE_PYM, ADDRESS, ",
        "TEL, FAX, POST_CODE, ",
        "LINK_MAN)",
        "values (#{manufactureCode,jdbcType=INTEGER}, #{manufactureName,jdbcType=VARCHAR}, ",
        "#{manufacturePym,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{tel,jdbcType=VARCHAR}, #{fax,jdbcType=VARCHAR}, #{postCode,jdbcType=VARCHAR}, ",
        "#{linkMan,jdbcType=VARCHAR})"
    })
    int insert(Manafacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MANAFACTURER
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Select({
        "select",
        "MANUFACTURE_CODE, MANUFACTURE_NAME, MANUFACTURE_PYM, ADDRESS, TEL, FAX, POST_CODE, ",
        "LINK_MAN",
        "from MANAFACTURER",
        "where MANUFACTURE_CODE = #{manufactureCode,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="MANUFACTURE_CODE", property="manufactureCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="MANUFACTURE_NAME", property="manufactureName", jdbcType=JdbcType.VARCHAR),
        @Result(column="MANUFACTURE_PYM", property="manufacturePym", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADDRESS", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="TEL", property="tel", jdbcType=JdbcType.VARCHAR),
        @Result(column="FAX", property="fax", jdbcType=JdbcType.VARCHAR),
        @Result(column="POST_CODE", property="postCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="LINK_MAN", property="linkMan", jdbcType=JdbcType.VARCHAR)
    })
    Manafacturer selectByPrimaryKey(Integer manufactureCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MANAFACTURER
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Select({
        "select",
        "MANUFACTURE_CODE, MANUFACTURE_NAME, MANUFACTURE_PYM, ADDRESS, TEL, FAX, POST_CODE, ",
        "LINK_MAN",
        "from MANAFACTURER"
    })
    @Results({
        @Result(column="MANUFACTURE_CODE", property="manufactureCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="MANUFACTURE_NAME", property="manufactureName", jdbcType=JdbcType.VARCHAR),
        @Result(column="MANUFACTURE_PYM", property="manufacturePym", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADDRESS", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="TEL", property="tel", jdbcType=JdbcType.VARCHAR),
        @Result(column="FAX", property="fax", jdbcType=JdbcType.VARCHAR),
        @Result(column="POST_CODE", property="postCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="LINK_MAN", property="linkMan", jdbcType=JdbcType.VARCHAR)
    })
    List<Manafacturer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MANAFACTURER
     *
     * @mbg.generated Mon Dec 02 16:05:57 CST 2019
     */
    @Update({
        "update MANAFACTURER",
        "set MANUFACTURE_NAME = #{manufactureName,jdbcType=VARCHAR},",
          "MANUFACTURE_PYM = #{manufacturePym,jdbcType=VARCHAR},",
          "ADDRESS = #{address,jdbcType=VARCHAR},",
          "TEL = #{tel,jdbcType=VARCHAR},",
          "FAX = #{fax,jdbcType=VARCHAR},",
          "POST_CODE = #{postCode,jdbcType=VARCHAR},",
          "LINK_MAN = #{linkMan,jdbcType=VARCHAR}",
        "where MANUFACTURE_CODE = #{manufactureCode,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Manafacturer record);
}